'use strict';
const $=s=>document.querySelector(s),desk=$('#desk');
const state={dataset:'imop',meta:null,channel:0,z:0,angle:25,pitch:.35,run:'',image:'raw',overlay:'fill',gain:1,projection:'mean',region3d:null,focusObject:null,opacity:.65,tab:'Explore',items:[],revision:null,dirty:false,recipe:{},tool:'navigate',pending:[],undo:[],runs:[],author:localStorage.getItem('studio-author')||'',generation:0};
const spaces=Object.fromEntries(['Explore','Process','Review','Compare','Annotate','Results'].map(t=>[t,{main:'projection',windows:[],initialized:false}]));let seq=0,topZ=3,refreshTimer=null;const active=()=>spaces[state.tab];
const names={projection:'Z projection',slice:'Single acquired slice',volume:'3D volume',process:'Processing recipe',annotations:'Annotations',results:'Runs & exports',layers:'Display controls'};
const imageCache=new Map(),pointCache=new Map();
function status(s,error=false){$('#status').textContent=s;$('#status').className=error?'error':''}
async function api(path,body){const response=await fetch(path,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Studio-Request':'1'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||response.statusText);return result}
function safe(action){return(...args)=>Promise.resolve().then(()=>action(...args)).catch(e=>status(e.message,true))}
function query(obj){return new URLSearchParams(Object.entries(obj).filter(([k,v])=>v!==null&&v!==undefined&&v!=='')).toString()}
function link(path,label){const a=document.createElement('a');a.href='/api/download?'+query({path});a.textContent=label;a.download=path.split('/').pop();return a}
async function bitmap(url){if(!imageCache.has(url)){if(imageCache.size>35){imageCache.delete(imageCache.keys().next().value)}imageCache.set(url,fetch(url).then(async r=>{if(!r.ok)throw Error((await r.json()).error);return createImageBitmap(await r.blob())}))}return imageCache.get(url)}
function runMeta(){return state.runs.find(r=>r.id===state.run)}
function canShow(run,type){return !run||run.scope==='volume'||(run.scope==='projection'&&type==='projection')||(run.scope==='slice'&&type==='slice'&&run.z===state.z)}
function snapshot(){state.undo.push(structuredClone(state.items));if(state.undo.length>50)state.undo.shift();state.dirty=true;if(typeof queueDraft==='function')queueDraft()}
function updateAnnotationPanels(){document.querySelectorAll('[data-annotation-list]').forEach(fillAnnotationList)}
function cancelDraft(){if(state.pending.length)status('Unfinished drawing cleared');state.pending=[]}
// Native-coordinate navigation. Camera state is separate from image/annotation data.
const cameras=new Map();
function navigation(v,key){
 if(!cameras.has(key))cameras.set(key,{zoom:1,pan:[0,0],yaw:25,pitch:.35});
 const cam=cameras.get(key);v.camera=cam;
 for(const prop of ['zoom','pan'])Object.defineProperty(v,prop,{get:()=>cam[prop],set:value=>cam[prop]=value,configurable:true});
 const controls=document.createElement('div');controls.className='view-navigation';controls.setAttribute('aria-label','Image navigation');
 const button=(label,fn,name)=>{const b=document.createElement('button');b.textContent=label;b.onclick=fn;if(name){b.setAttribute('aria-label',name);b.title=name}controls.append(b);return b};
 button('−',()=>zoomView(v,.8),'Zoom out');const level=document.createElement('output');level.className='zoom-level';controls.append(level);button('+',()=>zoomView(v,1.25),'Zoom in');button('Fit',()=>resetView(v),'Fit image to view');
 if(v.dataset.kind==='volume'){
  for(const [name,yaw,pitch] of [['Top',0,0],['Front',0,Math.PI/2],['Side',90,0],['Oblique',35,.55]])button(name,()=>{cam.yaw=yaw;cam.pitch=pitch;sync();scheduleDraw()});
  const label=document.createElement('label');label.textContent='Tilt';const tilt=document.createElement('input');tilt.type='range';tilt.min=-90;tilt.max=90;tilt.value=cam.pitch*180/Math.PI;tilt.setAttribute('aria-label','3D tilt');tilt.oninput=()=>{cam.pitch=+tilt.value*Math.PI/180;scheduleDraw()};label.append(tilt);controls.append(label);
  v.syncTilt=()=>tilt.value=cam.pitch*180/Math.PI;
 }else button('1:1',()=>{const c=v.querySelector('canvas');v.zoom=1/Math.min(c.clientWidth/state.meta.shape[3],c.clientHeight/state.meta.shape[2]);v.pan=[0,0];scheduleDraw()},'Show one screen pixel per image pixel');
 const move=document.createElement('select');move.setAttribute('aria-label','Navigation gesture');move.innerHTML=v.dataset.kind==='volume'?'<option value="orbit">Drag: orbit</option><option value="pan">Drag: pan</option>':'<option value="pan">Drag: pan</option>';move.onchange=()=>v.dragMode=move.value;v.dragMode=move.value;controls.append(move);
 function sync(){if(v.syncTilt)v.syncTilt();level.textContent=Math.round((v.dataset.kind==='volume'?v.zoom:Math.min(v.clientWidth/state.meta.shape[3],v.clientHeight/state.meta.shape[2])*v.zoom)*100)+'%'}
 v.syncNavigation=sync;v.append(controls);sync();
 const c=v.querySelector('canvas');c.tabIndex=0;
 c.addEventListener('keydown',e=>{if(['+','=','-','f','F','ArrowLeft','ArrowRight','ArrowUp','ArrowDown','PageUp','PageDown'].includes(e.key))e.preventDefault();if(e.key==='+'||e.key==='=')zoomView(v,1.25);else if(e.key==='-')zoomView(v,.8);else if(e.key.toLowerCase()==='f')resetView(v);else if(e.key==='PageUp'||e.key==='PageDown'){setDepth(state.z+(e.key==='PageUp'?1:-1))}else {const d={ArrowLeft:[40,0],ArrowRight:[-40,0],ArrowUp:[0,40],ArrowDown:[0,-40]}[e.key];if(d){v.pan=[v.pan[0]+d[0],v.pan[1]+d[1]];scheduleDraw()}}});
}
function zoomView(v,factor,anchor){
 const old=v.zoom,next=Math.max(.05,Math.min(40,old*factor)),ratio=next/old;
 const c=v.querySelector('canvas'),at=anchor||[c.clientWidth/2,c.clientHeight/2];
 v.pan=[at[0]-c.clientWidth/2-(at[0]-c.clientWidth/2-v.pan[0])*ratio,at[1]-c.clientHeight/2-(at[1]-c.clientHeight/2-v.pan[1])*ratio];v.zoom=next;scheduleDraw();
}
function resetView(v){v.zoom=1;v.pan=[0,0];if(v.camera){v.camera.yaw=25;v.camera.pitch=.35}scheduleDraw()}
function setDepth(z){if(!state.meta)return;cancelDraft();state.z=Math.max(0,Math.min(state.meta.shape[0]-1,z));$('#z').value=state.z;$('#zlabel').textContent=(state.z+1)+' / '+state.meta.shape[0];scheduleDraw()}
let depthTimer=null;
function stopDepth(){clearInterval(depthTimer);depthTimer=null;const b=$('#play-z');if(b)b.textContent='Play Z'}

function newViewport(kind,raw=false,key='main'){const div=document.createElement('div');div.className='viewport';div.dataset.kind=kind;div.raw=raw;const c=document.createElement('canvas');c.setAttribute('aria-label',names[kind]);const caption=document.createElement('div');caption.className='caption';div.append(c,caption);navigation(div,state.dataset+':'+(state.linked?'linked':state.tab+':'+key)+':'+kind);bindCanvas(div);return div}
function content(kind,raw=false,key='main'){return ['projection','slice','volume'].includes(kind)?newViewport(kind,raw,key):makeTool(kind)}
function addWindow(kind,raw=false){const win={id:++seq,kind,raw,x:Math.max(8,desk.clientWidth-400)-(active().windows.length%3)*20,y:20+(active().windows.length%3)*35,w:380,h:['projection','slice','volume'].includes(kind)?300:Math.min(560,desk.clientHeight-30),stack:++topZ};active().windows.push(win);return win}
function constrain(w){w.w=Math.min(w.w,desk.clientWidth-16);w.h=Math.min(w.h,desk.clientHeight-16);w.x=Math.max(8,Math.min(w.x,desk.clientWidth-w.w-8));w.y=Math.max(8,Math.min(w.y,desk.clientHeight-w.h-8))}
function place(w,el){constrain(w);Object.assign(el.style,{left:w.x+'px',top:w.y+'px',width:w.w+'px',height:w.h+'px',zIndex:w.stack})}
function renderLayout(){$('#zlabel').textContent=state.meta?(state.z+1)+' / '+state.meta.shape[0]:'';$('#view').value=['projection','slice','volume'].includes(active().main)?active().main:'projection';if(!active().initialized){active().initialized=true;if(state.tab==='Process')addWindow('process');if(state.tab==='Compare'){addWindow('slice',true);addWindow('projection')}if(state.tab==='Annotate')addWindow('annotations');if(state.tab==='Results')active().main='results'}
 $('#main-host').replaceChildren(content(active().main));$('#windows').replaceChildren();document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));
 for(const w of active().windows){const el=document.createElement('section');el.className='window';el.dataset.id=w.id;const bar=document.createElement('div');bar.className='bar';const title=document.createElement('span');title.textContent=names[w.kind]+(w.raw?' • raw':'');bar.append(title);for(const [label,fn] of [['Main',()=>{const old=active().main;active().main=w.kind;w.kind=old;w.raw=false;renderLayout()}],['Close',()=>{active().windows=active().windows.filter(x=>x.id!==w.id);renderLayout()}]]){const b=document.createElement('button');b.textContent=label;b.onclick=fn;bar.append(b)}if(['slice','projection','volume'].includes(w.kind)){const b=document.createElement('button');b.textContent=w.raw?'Use active run':'Raw only';b.onclick=()=>{w.raw=!w.raw;renderLayout()};bar.append(b)}const body=document.createElement('div');body.className='window-content';body.append(content(w.kind,w.raw,w.id));el.append(bar,body);const resize=document.createElement('button');resize.textContent='↘';resize.className='resize';resize.setAttribute('aria-label','Resize window with arrow keys');el.append(resize);place(w,el);
 const bind=(handle,size)=>{handle.onpointerdown=e=>{if(!size&&e.target.closest('button'))return;e.preventDefault();handle.setPointerCapture(e.pointerId);const old={...w},x=e.clientX,y=e.clientY;handle.onpointermove=m=>{if(size){w.w=Math.max(270,old.w+m.clientX-x);w.h=Math.max(200,old.h+m.clientY-y)}else{w.x=old.x+m.clientX-x;w.y=old.y+m.clientY-y}place(w,el);scheduleDraw()};handle.onpointerup=()=>handle.onpointermove=null}};bind(bar,false);bind(resize,true);resize.onkeydown=e=>{const d={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[e.key];if(d){e.preventDefault();w.w=Math.max(270,w.w+d[0]);w.h=Math.max(200,w.h+d[1]);place(w,el);scheduleDraw()}};el.onpointerdown=()=>{w.stack=++topZ;el.style.zIndex=w.stack};$('#windows').append(el)}scheduleDraw();}
// Coalesce input into the next display frame; never postpone it until input stops.
function scheduleDraw(){if(state.tab==='Review'){if(typeof scheduleReview==='function')scheduleReview();return}if(refreshTimer!==null)return;refreshTimer=requestAnimationFrame(()=>{refreshTimer=null;document.querySelectorAll('.viewport').forEach(v=>draw(v))})}
function gestureFrame(v){v.camera.movingUntil=performance.now()+140;clearTimeout(v.camera.settleTimer);v.camera.settleTimer=setTimeout(scheduleDraw,150);scheduleDraw()}
function wheelPixels(e,height){return e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?height:1)}
async function draw(v){if(!state.meta||!v.isConnected)return;if(v.syncNavigation)v.syncNavigation();const ticket=(v.ticket||0)+1;v.ticket=ticket;const c=v.querySelector('canvas'),caption=v.querySelector('.caption'),w=c.clientWidth,h=c.clientHeight;if(!w||!h)return;const dpr=Math.min(devicePixelRatio||1,2);const ctx=c.getContext('2d');const clearFrame=()=>{if(c.width!==Math.round(w*dpr)||c.height!==Math.round(h*dpr)){c.width=Math.round(w*dpr);c.height=Math.round(h*dpr)}ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#020608';ctx.fillRect(0,0,w,h)};const kind=v.dataset.kind,selected=v.overrideRun!==undefined?v.overrideRun:state.run,rm=state.runs.find(r=>r.id===selected),run=!v.raw&&state.image!=='raw'&&!rm?.historical?selected:'';caption.classList.remove('error');if(!caption.textContent)caption.textContent='Loading '+names[kind]+'…';try{
 if(run&&!canShow(rm,kind))throw Error('Selected run does not cover this view. Choose raw source or a volume run.');
 if(run&&state.image==='ridge-response'&&!rm?.ridge_response)throw Error('This run has no ridge response. Choose Raw source or Processed intensity.');
 if(kind==='volume'){const overlay=!v.raw&&state.overlay!=='none'&&rm?.method!=='preprocess'&&rm?.scope==='volume'?selected:'';const result=await channelPoints(run,overlay);if(ticket!==v.ticket||!v.isConnected)return;clearFrame();const [sx,sy,sz]=result.spacing;const bounds=result.bounds_native||[[0,0,0],[state.meta.shape[3],state.meta.shape[2],state.meta.shape[0]]],[[x0,y0,z0],[x1,y1,z1]]=bounds,iw=x1-x0,ih=y1-y0,nz=z1-z0,scale=Math.min(w,h)*.85*v.zoom/Math.max(iw*sx,ih*sy,nz*sz),angle=v.camera.yaw*Math.PI/180;const project=(x,y,z)=>{const xx=(x-(x0+x1)/2)*sx,yy=(y-(y0+y1)/2)*sy,zz=(z-(z0+z1)/2)*sz;const depth=zz*Math.cos(angle)-xx*Math.sin(angle);return [w/2+v.pan[0]+(xx*Math.cos(angle)+zz*Math.sin(angle))*scale,h/2+v.pan[1]+(yy*Math.cos(v.camera.pitch)-depth*Math.sin(v.camera.pitch))*scale,depth*Math.cos(v.camera.pitch)+yy*Math.sin(v.camera.pitch)]};const smooth=await renderVolume3D(v,ctx,w,h,{run,overlay,result,bounds,scale,angle,ticket});if(ticket!==v.ticket||!v.isConnected)return;const stride=performance.now()<(v.camera.movingUntil||0)?Math.max(1,Math.ceil(result.points.length/12000)):1;const pts=[];for(let i=0;i<result.points.length;i+=stride){const [x,y,z,a,id,rgb,channel]=result.points[i],setting=channelSettings()[channel],adjusted=Math.max(0,Math.min(1,(a*setting.brightness/100-.5)*setting.contrast/100+.5));pts.push([...project(x,y,z),adjusted,id,rgb])}pts.sort((a,b)=>a[2]-b[2]);for(const [x,y,z,a,id,rgb] of pts){if(smooth&&(!id||state.focusObject))continue;ctx.fillStyle=id?`rgba(${id*67%160+80},${id*113%160+80},${id*41%160+80},${Math.max(state.focusObject?.4:.15,a*state.opacity)})`:`rgba(${rgb.join(',')},${a})`;ctx.fillRect(x,y,state.focusObject?3:2,state.focusObject?3:2)}drawGuides3D(ctx,w,h,project,bounds,scale);v.project=project;v.samplePoints=result.activePoints;for(const it of [...state.items,...(state.pendingDomain==='volume'&&state.pending.length?[{type:state.tool,domain:'volume',channel:state.channel,points:state.pending}]:[])].filter(it=>['slice','volume'].includes(it.domain)&&it.channel===state.channel)){ctx.strokeStyle=it.id===state.selected?'#ffc778':'#5cdeff';ctx.lineWidth=it.id===state.selected?3:2;ctx.beginPath();it.points.forEach(([x,y],i)=>{const p=project(x,y,it.domain==='volume'?it.points[i][2]:it.z);if(it.type==='point'){ctx.moveTo(p[0]+4,p[1]);ctx.arc(p[0],p[1],4,0,Math.PI*2)}else i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1])});if(it.type==='polygon')ctx.closePath();ctx.stroke()}if(!state.focusObject)await drawResultGeometry(v,ctx,selected,kind,project);if(ticket!==v.ticket||!v.isConnected)return;caption.textContent=(v.raw?'Raw':rm?.title||rm?.method||'Source')+' • '+(state.focusObject?'C'+(state.channel+1)+' isolated candidate #'+state.focusObject.id:colorDescription()+' • '+(state.region3d?'selected region':'3D volume'))+(smooth?'':' • sampled points')+(overlay&&!state.focusObject?' • candidate colors':'');return}
 const url='/api/image?'+query({dataset:state.dataset,channel:state.channel,z:kind==='projection'?0:state.z,view:kind,run,kind:state.image==='ridge-response'?'ridge-response':'processed',gain:state.gain});const maskUrl=!v.raw&&selected&&state.overlay!=='none'&&rm?.method!=='preprocess'&&canShow(rm,kind)?'/api/image?'+query({dataset:state.dataset,channel:state.channel,z:kind==='projection'?0:state.z,view:kind,overlay:selected,style:state.overlay}):null;const [images,mask]=await Promise.all([Promise.all(displayChannels().map(ch=>channelBitmap('/api/image?'+query({dataset:state.dataset,channel:ch,z:kind==='projection'?0:state.z,view:kind,run:ch===state.channel?run:'',kind:state.image==='ridge-response'?'ridge-response':'processed',gain:state.gain,projection:state.projection,background:channelSettings()[ch].background}),ch))),maskUrl?bitmap(maskUrl):null]);if(ticket!==v.ticket||!v.isConnected)return;clearFrame();const iw=state.meta.shape[3],ih=state.meta.shape[2],s=Math.min(w/iw,h/ih)*v.zoom,ox=(w-iw*s)/2+v.pan[0],oy=(h-ih*s)/2+v.pan[1];v.transform={s,ox,oy};ctx.save();ctx.globalCompositeOperation='lighter';for(const im of images)ctx.drawImage(im,ox,oy,iw*s,ih*s);ctx.restore();drawGuides2D(ctx,w,h,s,ox,oy,iw,ih);let detail='';if(!v.raw&&selected&&state.overlay!=='none'&&rm?.method!=='preprocess'){if(canShow(rm,kind)){ctx.globalAlpha=state.opacity;ctx.drawImage(mask,ox,oy,iw*s,ih*s);ctx.globalAlpha=1;detail=' • candidate '+rm.method+' • run C'+(rm.channel+1)}else detail=' • overlay outside this scope'}
 ctx.save();ctx.translate(ox,oy);ctx.scale(s,s);const items=state.items.filter(it=>it.domain!=='volume'&&it.channel===state.channel&&(it.domain==='projection'?kind==='projection':kind==='slice'?it.z===state.z:kind==='projection'));for(const it of items)drawAnnotation(ctx,it,s);if(state.pending.length&&state.pendingDomain===kind)drawAnnotation(ctx,{type:state.tool,points:state.pending,status:'draft'},s);ctx.restore();await drawResultGeometry(v,ctx,selected,kind,null,s,ox,oy);if(ticket!==v.ticket||!v.isConnected)return;drawProbe(v,ctx,s,ox,oy);caption.textContent=`${v.raw?'Raw image':rm?.method||'Original image'} • ${kind==='projection'?({'max':'Maximum','mean':'Average','sum':'Sum'}[state.projection]+' Z projection'):names[kind]}${kind==='slice'?' • Z '+(state.z+1)+' / '+state.meta.shape[0]:''} • ${run?(state.image==='ridge-response'?'ridge response':'processed intensity'):'raw'} • ${colorDescription()} • full field${detail}`;
 }catch(e){if(ticket===v.ticket){caption.textContent=e.message;caption.classList.add('error')}}}
function drawAnnotation(ctx,it,s){ctx.strokeStyle=it.id===state.selected?'#ffc778':it.status==='rejected'?'#ff7f85':it.status==='uncertain'?'#ffda70':it.status==='draft'?'#ffffff':'#57ddff';ctx.fillStyle=ctx.strokeStyle;ctx.lineWidth=2/s;ctx.beginPath();it.points.forEach(([x,y],i)=>{if(it.type==='point'){ctx.moveTo(x+4/s,y);ctx.arc(x,y,4/s,0,Math.PI*2)}else i?ctx.lineTo(x,y):ctx.moveTo(x,y)});if(it.type==='polygon')ctx.closePath();ctx.stroke()}
function bindCanvas(v){
 const c=v.querySelector('canvas');let start=null,moved=false,zTravel=0,zTime=0;
 c.onpointerdown=e=>{if(e.button!==0&&e.button!==1)return;start={x:e.clientX,y:e.clientY,lastX:e.clientX,lastY:e.clientY,orbit:v.dataset.kind==='volume'&&v.dragMode!=='pan'&&!e.shiftKey&&e.button===0};moved=false;c.focus({preventScroll:true});c.setPointerCapture(e.pointerId)};
 c.onpointermove=e=>{if(!start)return;if(Math.hypot(e.clientX-start.x,e.clientY-start.y)>4)moved=true;const dx=e.clientX-start.lastX,dy=e.clientY-start.lastY;start.lastX=e.clientX;start.lastY=e.clientY;if(state.tool==='navigate'||v.dataset.kind==='volume'){if(start.orbit){v.camera.yaw+=dx*.3;v.camera.pitch=Math.max(-Math.PI/2,Math.min(Math.PI/2,v.camera.pitch+dy*.008))}else v.pan=[v.pan[0]+dx,v.pan[1]+dy];gestureFrame(v)}};
 const end=()=>{start=null;v.camera.movingUntil=0;scheduleDraw()};c.onpointercancel=end;c.onlostpointercapture=end;
 c.onpointerup=e=>{if(!start)return;end();if(moved)return;if(state.tool==='navigate'){inspectAt(v,e);return;}if(v.dataset.kind==='volume'){status('Draw on a source slice or projection, not the 3D point preview');return}const t=v.transform;if(!t)return;const box=c.getBoundingClientRect(),x=(e.clientX-box.left-t.ox)/t.s,y=(e.clientY-box.top-t.oy)/t.s;if(x<0||y<0||x>=state.meta.shape[3]||y>=state.meta.shape[2])return;const domain=v.dataset.kind;if(state.pending.length&&state.pendingDomain!==domain){status('Finish or discard the drawing before switching its view',true);return}state.pendingDomain=domain;state.pending.push([Math.min(x,state.meta.shape[3]-1),Math.min(y,state.meta.shape[2]-1)]);if(state.tool==='point')finishDrawing();else scheduleDraw()};
 c.addEventListener('wheel',e=>{e.preventDefault();const delta=wheelPixels(e,c.clientHeight);if(!delta)return;if(e.shiftKey&&!e.ctrlKey){const now=performance.now();if(now-zTime>250||Math.sign(delta)!==Math.sign(zTravel))zTravel=0;zTime=now;zTravel+=Math.max(-100,Math.min(100,delta));if(Math.abs(zTravel)>=80){setDepth(state.z+Math.sign(zTravel));zTravel%=80}return}const rect=c.getBoundingClientRect();zoomView(v,Math.exp(-Math.max(-100,Math.min(100,delta))*.0015),[e.clientX-rect.left,e.clientY-rect.top]);gestureFrame(v)},{passive:false});
 c.ondblclick=()=>{if(state.tool==='navigate')resetView(v)}
}
function finishDrawing(){const minimum={point:1,polyline:2,polygon:3}[state.tool];if(!minimum||state.pending.length<minimum){status('Add at least '+(minimum||1)+' points',true);return}snapshot();state.items.push({id:crypto.randomUUID(),type:state.tool,domain:state.pendingDomain,z:state.z,channel:state.channel,points:state.pending,status:'unreviewed',note:''});state.items[state.items.length-1].label=state.annotationLabel||'';state.pending=[];updateAnnotationPanels();scheduleDraw();if(typeof queueDraft==='function')queueDraft();status('Annotation added • unsaved')}
function makeTool(kind){const host=document.createElement('div');host.className='main-tool';const el=document.createElement('div');el.className='tool';host.append(el);
 if(kind==='process'){el.innerHTML=`<h2>Run a real algorithm</h2><p class="muted">Uses the selected dataset and channel. Raw files stay unchanged. Gaussian widths and minimum sizes use the processing grid.</p><label>Algorithm<select name="method"><option value="otsu">Otsu • connected regions</option><option value="watershed">Distance watershed • candidate objects</option><option value="sato">Sato • ridge network</option><option value="preprocess">Preprocessing only</option></select></label><label>Scope<select name="scope"><option value="volume">Full Z volume</option><option value="projection">Maximum Z projection</option><option value="slice">Current acquired plane</option></select></label><label>XY resolution<select name="factor"><option value="2">2× block mean • half XY resolution</option><option value="1">Native resolution</option><option value="4">4× block mean • quarter XY resolution</option></select></label><label>Input<select name="parent"><option value="">Original source</option></select></label><label>Gaussian smoothing σ (XY pixels)<input name="sigma" type="number" min="0" max="5" step=".2" value="0"></label><label>Subtract Gaussian background σ (0 = off)<input name="background" type="number" min="0" max="64" value="0"></label><label><input name="normalize" type="checkbox"> Normalize 1–99.5 percentile</label><label>Otsu threshold multiplier<input name="threshold" type="number" min=".1" max="4" step=".1" value="1"></label><label>Minimum foreground component (voxels/pixels)<input name="min_size" type="number" min="1" value="30"></label><label>Watershed seed distance (grid pixels)<input name="distance" type="number" min="1" value="5"></label><button data-run>Run selected method</button><button data-batch>Run all 3 local methods</button><div class="tool-progress"></div><p class="muted">Sato components describe networks, not individual neurons. These are classical algorithms; existing learned-model runs are not rerun here.</p>`;const parent=el.querySelector('[name=parent]');for(const r of state.runs.filter(r=>r.scope==='volume'&&!r.historical&&!r.external)){const o=document.createElement('option');o.value=r.id;o.textContent=r.method+' • '+r.id.slice(0,6)+' • '+r.factor+'×';parent.append(o)}
 el.querySelectorAll('[name]').forEach(n=>{if(state.recipe[n.name]!==undefined){if(n.type==='checkbox')n.checked=state.recipe[n.name];else n.value=state.recipe[n.name]}n.addEventListener('change',()=>state.recipe[n.name]=n.type==='checkbox'?n.checked:n.value)});el.querySelector('[data-batch]').onclick=safe(async()=>{const params={dataset:state.dataset,channel:state.channel,z:state.z};el.querySelectorAll('[name]').forEach(n=>params[n.name]=n.type==='checkbox'?n.checked:n.value);for(const method of ['otsu','watershed','sato'])await api('/api/run',{...params,method});status('Queued Otsu, watershed and Sato with the same preprocessing');pollJobs()});el.querySelector('[data-run]').onclick=safe(async()=>{const params={dataset:state.dataset,channel:state.channel,z:state.z};el.querySelectorAll('[name]').forEach(n=>params[n.name]=n.type==='checkbox'?n.checked:n.value);const job=await api('/api/run',params);status('Run queued '+job.id.slice(0,6));pollJobs()});
 }
 if(kind==='layers'){el.innerHTML=`<h2>Display</h2><label>Brightness<input data-gain type="range" min=".1" max="5" step=".1" value="${state.gain}"></label><label>Mask opacity<input data-opacity type="range" min="0" max="1" step=".05" value="${state.opacity}"></label><p class="muted">Display changes do not modify processing inputs. Wheel to zoom, drag to pan, double-click to fit. On 3D, drag to rotate.</p><button data-fit>Fit all image views</button>`;el.querySelector('[data-gain]').oninput=e=>{state.gain=+e.target.value;scheduleDraw()};el.querySelector('[data-opacity]').oninput=e=>{state.opacity=+e.target.value;scheduleDraw()};el.querySelector('[data-fit]').onclick=()=>{document.querySelectorAll('.viewport').forEach(v=>{v.zoom=1;v.pan=[0,0]});scheduleDraw()}}
 if(kind==='annotations'){el.innerHTML=`<h2>Manual annotations</h2><label>Annotator<input data-author placeholder="Your name"></label><label>Tool<select data-tool><option value="navigate">Pan / zoom</option><option value="point">Count point</option><option value="polygon">Cell outline (polygon)</option><option value="polyline">Neurite trace (polyline)</option></select></label><p class="muted">Click vertices on the main image or a floating slice/projection. Finish to add a trace/outline. Annotations use native source coordinates and retain channel and Z.</p><div class="buttons"><button data-finish>Finish drawing</button><button data-discard>Discard drawing</button><button data-undo>Undo edit</button></div><div class="buttons"><button data-save>Save revision</button><button data-reload>Reload saved</button></div><label>Import ImageJ RoiSet.zip into this dataset<input data-import type="file" accept=".zip"></label><p class="muted">Import previews annotations as unreviewed; confirm the archive belongs to this image before saving. Projection traces have 2D lengths, not reconstructed 3D lengths.</p><div data-export></div><div data-annotation-list></div>`;el.querySelector('[data-author]').value=state.author;el.querySelector('[data-author]').oninput=e=>{state.author=e.target.value;localStorage.setItem('studio-author',state.author)};el.querySelector('[data-tool]').value=state.tool;el.querySelector('[data-tool]').onchange=e=>{cancelDraft();state.tool=e.target.value;document.querySelectorAll('[data-tool]').forEach(x=>x.value=state.tool)};el.querySelector('[data-finish]').onclick=finishDrawing;el.querySelector('[data-discard]').onclick=()=>{cancelDraft();scheduleDraw()};el.querySelector('[data-undo]').onclick=()=>{if(state.undo.length){state.items=state.undo.pop();state.dirty=true;updateAnnotationPanels();scheduleDraw()}};el.querySelector('[data-save]').onclick=safe(saveAnnotations);el.querySelector('[data-reload]').onclick=safe(async()=>{if(state.dirty&&!confirm('Discard unsaved annotation changes and load the saved revision?'))return;await loadAnnotations();updateAnnotationPanels();scheduleDraw()});el.querySelector('[data-import]').onchange=safe(async e=>{const f=e.target.files[0];if(!f)return;const bytes=new Uint8Array(await f.arrayBuffer());if(bytes.length>5e6)throw Error('Archive limit is 5 MB');let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const result=await api('/api/import-rois',{dataset:state.dataset,data:btoa(binary)});snapshot();state.items.push(...result.items);updateAnnotationPanels();scheduleDraw();status('Imported '+result.items.length+' ROIs • unsaved')});fillAnnotationList(el.querySelector('[data-annotation-list]'));fillExports(el.querySelector('[data-export]'))}
 if(kind==='results'){el.innerHTML='<h2>Saved runs</h2><div data-run-list></div><h2>Jobs</h2><div class="tool-progress"></div>';fillRuns(el.querySelector('[data-run-list]'));pollJobs()}
 return host}
function fillAnnotationList(el){el.replaceChildren();for(const [i,it] of state.items.entries()){const row=document.createElement('div');row.className='annotation-row';const text=document.createElement('span');text.textContent=`${i+1}. ${it.type} • C${it.channel+1} • ${it.domain==='slice'?'Z'+(it.z+1):it.domain==='volume'?'3D':'projection'}`;const sel=document.createElement('select');for(const name of ['unreviewed','accepted','uncertain','rejected']){const o=document.createElement('option');o.textContent=name;sel.append(o)}sel.value=it.status;sel.onchange=()=>{snapshot();it.status=sel.value;scheduleDraw()};const del=document.createElement('button');del.textContent='Delete';del.onclick=()=>{snapshot();state.items=state.items.filter(x=>x.id!==it.id);updateAnnotationPanels();scheduleDraw()};const show=document.createElement('button');show.textContent='Show';show.onclick=()=>{cancelDraft();state.channel=it.channel;$('#channel').value=it.channel;state.z=it.z;$('#z').value=it.z;state.mode=it.domain;active().main=it.domain;renderLayout()};row.append(text,sel,show,del);el.append(row)}}
function fillExports(el){el.replaceChildren();if(state.revision){const base='annotations/'+state.dataset+'/'+state.revision+'/';for(const [name,label] of [['annotation-package.zip','Download package'],['RoiSet.zip','ImageJ ROIs'],['measurements.csv','Measurements CSV'],['annotations.json','Provenance JSON']]){el.append(link(base+name,label),document.createElement('br'))}const p=document.createElement('p');p.className='muted';p.textContent='Saved revision '+state.revision.slice(0,8)+' • CSV separates planar and 3D trace measurements. Keep the JSON with the ROI archive.';el.append(p)}}
async function saveAnnotations(){if(state.pending.length)throw Error('Finish or discard the pending drawing first');const key=state.dataset;const savedItems=JSON.stringify(state.items);const doc=await api('/api/annotations',{dataset:key,base_revision:state.revision,author:state.author,items:state.items});if(key!==state.dataset)return;state.revision=doc.revision;state.dirty=JSON.stringify(state.items)!==savedItems;document.querySelectorAll('[data-export]').forEach(fillExports);status('Annotations saved to disk • '+doc.revision.slice(0,8))}
async function loadAnnotations(){const d=await api('/api/annotations?'+query({dataset:state.dataset}));state.items=d.items;state.revision=d.revision;state.dirty=false;state.undo=[];state.pending=[]}
function fillRuns(el){el.replaceChildren();if(!state.runs.length){el.textContent='No completed runs for this dataset. Open Process to create one.';return}for(const r of [...state.runs].reverse()){const row=document.createElement('div');row.className='run-row';const title=document.createElement('div');title.textContent=`${r.method} • ${r.scope} • C${r.channel+1} • ${r.factor}× XY • ${r.objects} ${r.method==='sato'?'network components':'candidate regions'}`;const small=document.createElement('div');small.className='muted';small.textContent=r.id.slice(0,8)+' • '+r.seconds+' s • '+r.meaning;const load=document.createElement('button');load.textContent='View result';load.onclick=()=>{state.run=r.id;state.channel=r.channel;$('#channel').value=r.channel;state.image='processed';$('#run').value=r.id;$('#image').value='processed';active().main=r.scope==='projection'?'projection':'slice';if(r.scope==='slice'){state.z=r.z;$('#z').value=r.z}state.tab='Explore';active().main=r.scope==='projection'?'projection':'slice';renderLayout()};const rerun=document.createElement('button');rerun.textContent='Rerun recipe';rerun.onclick=safe(async()=>{await api('/api/run',r.parameters);status('Identical recipe queued');pollJobs()});if(r.external)rerun.disabled=true;row.append(title,small,load,rerun,document.createElement('br'));for(const [name,label] of [['processed.tif','Image TIFF'],['labels.tif','Labels TIFF'],['objects.csv','Original algorithm CSV'],['run.json','Recipe/provenance']])row.append(link('runs/'+r.id+'/'+name,label),document.createTextNode(' · '));el.append(row)}}
async function loadRuns(){const key=state.dataset,runs=await api('/api/runs?'+query({dataset:key}));if(key!==state.dataset)return;state.runs=runs.sort((a,b)=>(a.created||0)-(b.created||0));const select=$('#run');select.replaceChildren(new Option('None',''));for(const r of runs)select.add(new Option(r.method+' • '+r.scope+' • '+r.id.slice(0,6),r.id));select.value=state.run;document.querySelectorAll('[data-run-list]').forEach(fillRuns)}
let polling=false,seenJobs=new Set();async function pollJobs(){if(polling)return;polling=true;try{const jobs=await api('/api/jobs');document.querySelectorAll('.tool-progress').forEach(el=>{el.replaceChildren();for(const j of jobs.filter(x=>x.dataset===state.dataset)){const row=document.createElement('div');row.textContent=j.id.slice(0,6)+' • '+j.status+' • '+(j.error||j.message||'');if(['queued','running'].includes(j.status)){const b=document.createElement('button');b.textContent='Cancel';b.onclick=safe(()=>api('/api/cancel',{id:j.id}));row.append(b)}if(j.status==='completed'){const view=document.createElement('button');view.textContent='View result';view.onclick=()=>{if(j.dataset===state.dataset)chooseResult(j.id)};row.append(view)}el.append(row)}});for(const j of jobs){if(j.status==='completed'&&!seenJobs.has(j.id)){seenJobs.add(j.id);await loadRuns();status('Completed '+j.id.slice(0,6)+' • select it under Algorithm results')}if(j.status==='failed')seenJobs.add(j.id)}}catch(e){status(e.message,true)}finally{polling=false}}
async function selectDataset(key){if(state.dirty&&!confirm('Discard unsaved annotations before switching datasets?')){$('#dataset').value=state.dataset;return}stopDepth();state.dataset=key;state.region3d=null;state.focusObject=null;$('#dataset').value=key;state.recipe.parent='';state.meta=null;state.run='';state.image='raw';state.channel=0;state.z=0;state.tool='navigate';state.pending=[];state.generation++;$('#main-host').replaceChildren();$('#windows').replaceChildren();const generation=state.generation;status('Loading native image metadata…');const d=await api('/api/dataset?'+query({id:key}));if(generation!==state.generation)return;state.meta=d;state.z=Math.floor(d.shape[0]/2);state.recipe.factor=d.shape[0]*d.shape[2]*d.shape[3]>32000000?4:2;$('#channel').replaceChildren(...d.channels.map((s,i)=>new Option((i+1)+' · '+s,i)));$('#z').max=d.shape[0]-1;$('#z').value=state.z;$('#image').value='raw';$('#meta').textContent=d.shape[3]+' × '+d.shape[2]+' • '+d.shape[0]+' Z • '+d.dtype;await loadRuns();await loadAnnotations();renderLayout();status('Loaded '+d.name+' • source data unchanged')}
$('#dataset').onchange=safe(e=>selectDataset(e.target.value));$('#channel').onchange=e=>{cancelDraft();state.channel=+e.target.value;state.image='raw';$('#image').value='raw';if(runMeta()?.channel!==state.channel){state.run='';$('#run').value=''}if(state.runs.find(r=>r.id===state.compareRun)?.channel!==state.channel)state.compareRun='';if(typeof resetReviewSelection==='function')resetReviewSelection();renderLayout()};$('#z').oninput=e=>{cancelDraft();state.z=+e.target.value;$('#zlabel').textContent=(state.z+1)+' / '+state.meta.shape[0];scheduleDraw()};$('#angle').oninput=e=>{document.querySelectorAll('.viewport[data-kind=volume]').forEach(v=>v.camera.yaw=+e.target.value);scheduleDraw()};$('#run').onchange=e=>{state.run=e.target.value;if(state.image==='processed'&&runMeta()){state.channel=runMeta().channel;$('#channel').value=state.channel}scheduleDraw()};$('#image').onchange=e=>{state.image=e.target.value;if(state.image==='processed'&&runMeta()){state.channel=runMeta().channel;$('#channel').value=state.channel}scheduleDraw()};$('#overlay').onchange=e=>{state.overlay=e.target.value;scheduleDraw()};$('#view').onchange=e=>{cancelDraft();active().main=e.target.value;renderLayout()};$('#new-window').onclick=()=>{addWindow($('#open').value);renderLayout()};$('#open-main').onclick=()=>{active().main=$('#open').value;renderLayout()};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{cancelDraft();stopDepth();state.tab=b.dataset.tab;renderLayout()});$('#focus').onclick=()=>{document.body.classList.toggle('focus');scheduleDraw()};$('#fullscreen').onclick=safe(async()=>{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()});window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue=''}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){cancelDraft();state.tool='navigate';document.querySelectorAll('[data-tool]').forEach(x=>x.value='navigate');scheduleDraw()}});new ResizeObserver(()=>{document.querySelectorAll('.window').forEach(el=>{const w=active().windows.find(w=>w.id===+el.dataset.id);if(w)place(w,el)});scheduleDraw()}).observe(desk);setInterval(pollJobs,2000);
(async()=>{const datasets=await api('/api/datasets');$('#dataset').replaceChildren(...datasets.map(d=>new Option(d.name,d.id)));await selectDataset(datasets.some(d=>d.id==='imop')?'imop':datasets[0].id);$('#zlabel').textContent=(state.z+1)+' / '+state.meta.shape[0]})().catch(e=>status(e.message,true));

$('#previous-z').onclick=()=>setDepth(state.z-1);$('#next-z').onclick=()=>setDepth(state.z+1);$('#play-z').onclick=()=>{if(depthTimer){stopDepth();return}if(state.z===state.meta.shape[0]-1)setDepth(0);$('#play-z').textContent='Pause Z';depthTimer=setInterval(()=>{if(state.z>=state.meta.shape[0]-1){stopDepth();return}setDepth(state.z+1)},500)};document.addEventListener('visibilitychange',()=>{if(document.hidden)stopDepth()});
