'use strict';
const nativeFetch=window.fetch.bind(window),pendingRequests=new Map();let requestID=0;
const boot=document.createElement('div');boot.id='boot';boot.innerHTML='<div><span class="boot-mark">◈</span><h1>Your images. Your field of view.</h1><p id="boot-status">Starting the image engine…</p><p class="muted">First launch downloads the scientific image engine.<br>Scans and processing stay in your browser.</p></div>';document.body.append(boot);
const workerVersion=new URL(document.currentScript.src).search;
let startWorker,denyWorker;
const workerReady=new Promise((resolve,reject)=>{startWorker=resolve;denyWorker=reject});
function launch(){const w=new Worker('./worker.js'+workerVersion);w.onmessage=({data})=>{if(data.progress){if(document.querySelector('#boot-status'))document.querySelector('#boot-status').textContent=data.progress;if(data.progress.startsWith('Ready'))boot.remove();return}if(data.fatal){document.querySelector('#boot-status').textContent='Unable to start: '+data.fatal;return}const p=pendingRequests.get(data.id);if(p){pendingRequests.delete(data.id);p.resolve(new Response(data.data,{status:data.status,headers:{'Content-Type':data.type}}))}};w.onerror=e=>{document.querySelector('#boot-status')?.replaceChildren(document.createTextNode('Engine failed to load. Check your connection and reload.'));for(const p of pendingRequests.values())p.reject(Error('Image engine failed'));pendingRequests.clear()};startWorker(w)}
if(navigator.locks){navigator.locks.request('field-studio-workspace',{ifAvailable:true},lock=>{if(!lock){document.querySelector('#boot-status').textContent='This workspace is open in another tab. Close that tab, then reload here.';denyWorker(Error('Workspace already open'));return}launch();return new Promise(()=>{})})}else launch();
window.fetch=async(input,options={})=>{const raw=typeof input==='string'?input:input.url;const u=new URL(raw,location.href);if(!u.pathname.startsWith('/api/'))return nativeFetch(input,options);const worker=await workerReady;let body=options.body;if(typeof body==='string')body=new TextEncoder().encode(body);else if(body instanceof Blob)body=await body.arrayBuffer();const id=++requestID;return new Promise((resolve,reject)=>{pendingRequests.set(id,{resolve,reject});worker.postMessage({id,path:u.pathname+u.search,method:options.method||'GET',body:body||new Uint8Array()})})};
document.addEventListener('click',async e=>{const a=e.target.closest('a');if(!a||!a.getAttribute('href')?.startsWith('/api/'))return;e.preventDefault();try{const r=await fetch(a.getAttribute('href'));if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),link=document.createElement('a');link.href=url;link.download=a.download||'field-export';link.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){alert(e.message)}});
window.addEventListener('DOMContentLoaded',()=>{const exportButton=document.createElement('button');exportButton.textContent='Back up workspace';exportButton.onclick=async()=>{exportButton.disabled=true;try{const r=await fetch('/api/workspace-export');if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='field-workspace-'+new Date().toISOString().slice(0,10)+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}catch(e){alert(e.message)}finally{exportButton.disabled=false}};document.querySelector('header').append(exportButton);const restore=document.createElement('button');restore.textContent='Restore backup';const file=document.createElement('input');file.type='file';file.accept='.zip';file.hidden=true;restore.onclick=()=>file.click();file.onchange=async()=>{try{const r=await fetch('/api/workspace-restore',{method:'POST',body:file.files[0]});if(!r.ok)throw Error((await r.json()).error);location.reload()}catch(e){alert(e.message)}};document.querySelector('#toolbar').append(restore,file);const banner=document.createElement('div');banner.className='shared-banner';banner.textContent='Free browser demo · real neuron & hair-cell scans · your scans stay on this device · saved in this browser—back up to keep a portable copy';document.querySelector('nav').before(banner)});
