'use strict';
state.mode='projection';state.compare=true;state.linked=true;state.compareRun='';state.cursor=null;
const geometryCache=new Map();
async function drawResultGeometry(v,ctx,selected,kind,project,s=1,ox=0,oy=0){
 if(v.raw||!selected||state.overlay==='none')return;const r=state.runs.find(r=>r.id===selected);if(!r?.geometry||!canShow(r,kind))return;
 const key=state.dataset+':'+selected;if(!geometryCache.has(key))geometryCache.set(key,api('/api/geometry?'+query({dataset:state.dataset,run:selected})));
 const ticket=v.ticket;const g=await geometryCache.get(key);if(!v.isConnected||ticket!==v.ticket)return;
 const point=p=>project?project(...p):[ox+p[0]*s,oy+p[1]*s];ctx.save();ctx.strokeStyle='#79e9cc';ctx.fillStyle='#79e9cc';ctx.lineWidth=1.5;ctx.globalAlpha=state.opacity;
 for(const box of g.boxes||[]){const a=point([box[0],box[1],0]),b=point([box[2],box[3],0]);ctx.strokeRect(a[0],a[1],b[0]-a[0],b[1]-a[1])}
 for(const p of g.points||[]){if(kind==='slice'&&Math.abs(p[2]-state.z)>.75)continue;const a=point(p);ctx.beginPath();ctx.arc(a[0],a[1],4,0,Math.PI*2);ctx.stroke()}
 for(const path of g.paths||[]){ctx.beginPath();let on=false;for(const p of path.points){const a=point(p),visible=kind!=='slice'||Math.abs(p[2]-state.z)<=.75;if(visible&&on)ctx.lineTo(a[0],a[1]);else ctx.moveTo(a[0],a[1]);on=visible}ctx.stroke()}
 ctx.restore();
}
function drawProbe(v,ctx,s,ox,oy){if(!state.cursor)return;const [x,y]=state.cursor;ctx.save();ctx.strokeStyle='#ffd98c';ctx.lineWidth=1;const xx=ox+x*s,yy=oy+y*s;ctx.beginPath();ctx.moveTo(xx-10,yy);ctx.lineTo(xx+10,yy);ctx.moveTo(xx,yy-10);ctx.lineTo(xx,yy+10);ctx.stroke();ctx.restore()}
async function inspectAt(v,e){if(!v.transform||v.dataset.kind==='volume')return;const box=v.querySelector('canvas').getBoundingClientRect(),t=v.transform,x=Math.round((e.clientX-box.left-t.ox)/t.s),y=Math.round((e.clientY-box.top-t.oy)/t.s);if(x<0||y<0||x>=state.meta.shape[3]||y>=state.meta.shape[2])return;state.cursor=[x,y];scheduleDraw();try{const result=await api('/api/probe?'+query({dataset:state.dataset,channel:state.channel,z:state.z,x,y,view:v.dataset.kind,run:state.run}));status(`X ${x}, Y ${y} • intensity ${result.intensity} • ${result.objects.length?'candidate IDs '+result.objects.slice(0,6).join(', '):'no candidate at this pixel'}${result.peak_z!==undefined?' • brightest Z '+(result.peak_z+1):''}`)}catch(e){status(e.message,true)}}
function chooseResult(id){const r=state.runs.find(r=>r.id===id);state.run=id;$('#run').value=id;state.image=r?.method==='preprocess'?'processed':'raw';$('#image').value=state.image;$('#show-processed').checked=state.image==='processed';if(typeof resetReviewSelection==='function')resetReviewSelection();if(r){state.channel=r.channel;$('#channel').value=r.channel;if(r.scope==='projection')state.mode='projection';if(r.scope==='slice'){state.mode='slice';setDepth(r.z)}}cancelDraft();renderLayout()}
function resultCatalog(){const list=$('#result-list');list.replaceChildren();$('#result-count').textContent=state.runs.length;
 const raw=document.createElement('button');raw.className='result-button'+(!state.run?' active':'');raw.textContent='Original image';raw.onclick=()=>chooseResult('');list.append(raw);
 for(const [label,rows] of [['Your runs',state.runs.filter(r=>!r.historical).reverse()],['Earlier algorithm results',state.runs.filter(r=>r.historical)]]){if(!rows.length)continue;const title=document.createElement('div');title.className='result-section';title.textContent=label;list.append(title);for(const r of rows){const b=document.createElement('button');b.className='result-button'+(r.id===state.run?' active':'');b.dataset.result=r.id;const title=document.createElement('div');title.textContent=r.title||r.method;const subtitle=document.createElement('span');subtitle.textContent=(r.scope==='volume'?'3D stack':r.scope==='projection'?'2D projection':'Z '+(r.z+1))+' • C'+(r.channel+1)+(r.historical?' • saved output':' • '+r.id.slice(0,5));b.append(title,subtitle);b.onclick=()=>chooseResult(r.id);list.append(b)}}
 if(!state.runs.length){const p=document.createElement('p');p.className='muted';p.textContent='No results yet. Choose Process to run algorithms on this image.';list.append(p)}
 const current=runMeta();if(current){const actions=document.createElement('div');actions.className='selected-actions';const info=document.createElement('p');info.className='muted';info.textContent=current.historical?'Saved prior result. Previewing it does not rerun the model.':'Saved run '+current.id.slice(0,8)+' • '+current.scope+' • '+current.factor+'× XY';actions.append(info);const download=document.createElement('a');download.href='/api/result-file?'+query({run:current.id,kind:current.geometry&&!current.mask_path?'geometry':'labels'});download.download=current.geometry&&!current.mask_path?'geometry.json':'original-labels.tif';download.textContent=current.geometry&&!current.mask_path?'Download geometry':'Download original labels';if(current.method==='preprocess'&&!current.historical){download.href='/api/download?'+query({path:'runs/'+current.id+'/processed.tif'});download.download='processed.ome.tif';download.textContent='Download processed image'}actions.append(download);if(!current.historical&&current.method!=='preprocess'){actions.append(link('runs/'+current.id+'/processed.tif','Download processed image'),link('runs/'+current.id+'/objects.csv','Original algorithm CSV'))}if(!current.historical&&current.scope==='volume'){const review=document.createElement('button');review.textContent='Review in XY / XZ / YZ';review.onclick=()=>{state.tab='Review';renderLayout()};actions.append(review)}if(!current.historical){const edit=document.createElement('button');edit.textContent='Edit recipe & rerun';edit.onclick=()=>{state.recipe={...current.parameters,units:current.parameters.units||'grid',sato_mode:current.sato_mode||'volume'};state.tab='Process';renderLayout()};actions.append(edit)}list.prepend(actions)}
 const compare=$('#comparison');compare.replaceChildren(new Option('Raw source',''));for(const r of state.runs.filter(r=>r.channel===state.channel))compare.add(new Option(r.title||r.method,r.id));compare.value=state.compareRun;
}
// Retain optional floating windows; standard review starts with linked raw/result panes.
const legacyLayout=renderLayout;
renderLayout=function(){if(!state.meta)return;if(state.tab==='Review'){renderReviewWorkspace();return}active().initialized=true;active().main=state.mode;$('#zlabel').textContent=(state.z+1)+' / '+state.meta.shape[0];$('#view').value=state.mode;$('#processed-label').hidden=!state.run||!!runMeta()?.historical;
 document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===state.mode));
 const main=$('#main-host');main.classList.remove('volume-review-host');main.replaceChildren();const comparing=state.compare&&!!state.run;main.classList.toggle('compare-grid',comparing);
 if(comparing){const left=newViewport(state.mode,!state.compareRun,'comparison');left.overrideRun=state.compareRun;main.append(left)}
 main.append(newViewport(state.mode,false,'selected'));
 const panel=$('#task-panel');panel.replaceChildren();panel.hidden=state.tab==='Explore';if(!panel.hidden){const tool=makeTool(state.tab==='Process'?'process':'annotations');if(state.tab==='Process'){const form=tool.querySelector('.tool'),labels=[...form.children].filter(e=>e.tagName==='LABEL'),advanced=document.createElement('details'),summary=document.createElement('summary');summary.textContent='Preprocessing & settings • '+form.querySelector('[name=factor]').value+'× XY';form.querySelector('[name=factor]').addEventListener('change',e=>summary.textContent='Preprocessing & settings • '+e.target.value+'× XY');advanced.append(summary);labels.slice(2).forEach(e=>advanced.append(e));form.insertBefore(advanced,form.querySelector('[data-run]'))}panel.append(tool)}
 $('#windows').replaceChildren();for(const win of active().windows){const el=document.createElement('section');el.className='window';place(win,el);const bar=document.createElement('div');bar.className='bar';const label=document.createElement('span');label.textContent=names[win.kind];const close=document.createElement('button');close.textContent='Close';close.onclick=()=>{active().windows=active().windows.filter(w=>w.id!==win.id);renderLayout()};bar.append(label,close);if(['slice','projection','volume'].includes(win.kind)){const promote=document.createElement('button');promote.textContent='Main';promote.onclick=()=>{const old=state.mode;state.mode=win.kind;win.kind=old;renderLayout()};bar.append(promote)}const body=document.createElement('div');body.className='window-content';body.append(content(win.kind,win.raw,win.id));el.append(bar,body);const resize=document.createElement('button');resize.className='resize';resize.textContent='↘';resize.setAttribute('aria-label','Resize window');resize.onpointerdown=e=>{resize.setPointerCapture(e.pointerId);const start=[e.clientX,e.clientY,win.w,win.h];resize.onpointermove=m=>{win.w=Math.max(270,start[2]+m.clientX-start[0]);win.h=Math.max(200,start[3]+m.clientY-start[1]);place(win,el);scheduleDraw()};resize.onpointerup=()=>resize.onpointermove=null};resize.onkeydown=e=>{const d={ArrowLeft:[-20,0],ArrowRight:[20,0],ArrowUp:[0,-20],ArrowDown:[0,20]}[e.key];if(d){e.preventDefault();win.w=Math.max(270,win.w+d[0]);win.h=Math.max(200,win.h+d[1]);place(win,el);scheduleDraw()}};el.append(resize);bar.onpointerdown=e=>{if(e.target.closest('button'))return;bar.setPointerCapture(e.pointerId);const start=[e.clientX,e.clientY,win.x,win.y];bar.onpointermove=m=>{win.x=start[2]+m.clientX-start[0];win.y=start[3]+m.clientY-start[1];place(win,el)};bar.onpointerup=()=>bar.onpointermove=null};$('#windows').append(el)}
 resultCatalog();scheduleDraw();
};
const originalLoadRuns=loadRuns;loadRuns=async function(){await originalLoadRuns();resultCatalog()};
$('#compare-raw').onchange=e=>{state.compare=e.target.checked;renderLayout()};$('#comparison').onchange=e=>{state.compareRun=e.target.value;renderLayout()};$('#link-views').onchange=e=>{state.linked=e.target.checked;renderLayout()};$('#show-processed').onchange=e=>{state.image=e.target.checked?'processed':'raw';$('#image').value=state.image;scheduleDraw()};$('#more-tools').onclick=()=>$('#toolbar').hidden=!$('#toolbar').hidden;
document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;cancelDraft();renderLayout()});$('#view').onchange=e=>{state.mode=e.target.value;renderLayout()};$('#open-main').onclick=()=>{const mode=$('#open').value;if(['projection','slice','volume'].includes(mode)){state.mode=mode;renderLayout()}else{addWindow(mode);renderLayout()}};
const originalDataset=selectDataset;selectDataset=async function(key){state.compareRun='';state.cursor=null;await originalDataset(key)};$('#dataset').onchange=safe(e=>selectDataset(e.target.value));
$('#import-source').onclick=()=>$('#source-file').click();$('#source-file').onchange=e=>{if(!e.target.files[0])return;$('#import-name').textContent=e.target.files[0].name;$('#import-status').textContent='';$('#import-dialog').showModal()};$('#cancel-import').onclick=()=>$('#import-dialog').close();
$('#import-form').onsubmit=async e=>{e.preventDefault();const file=$('#source-file').files[0],form=new FormData(e.target),params={name:file.name,axes:form.get('axes'),xy:form.get('xy'),z:form.get('z')};if((params.xy&&!params.z)||(!params.xy&&params.z)){$('#import-status').textContent='Supply both XY and Z spacing, or leave both blank.';return}const button=e.target.querySelector('[type=submit]');button.disabled=true;$('#import-status').textContent='Importing and reading image…';try{const response=await fetch('/api/import-source?'+query(params),{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Studio-Request':'1'},body:file});const d=await response.json();if(!response.ok)throw Error(d.error);$('#dataset').add(new Option(d.name,d.id));$('#dataset').value=d.id;await selectDataset(d.id);$('#import-dialog').close();status('Image imported • ready to process or annotate')}catch(err){$('#import-status').textContent=err.message}finally{button.disabled=false}};
