'use strict';
// Assistant plans are data. This controller has no arbitrary execution or write actions.
const fieldAssistant={history:[],config:null,busy:false,token:'',endpoint:localStorage.getItem('field-assistant-server')||'',snapshot:null};
const aiButton=document.createElement('button');aiButton.id='assistant-open';aiButton.textContent='✦ Ask AI';aiButton.setAttribute('aria-expanded','false');aiButton.setAttribute('aria-controls','assistant-panel');$('#start-task').after(aiButton);
const aiPanel=document.createElement('aside');aiPanel.id='assistant-panel';aiPanel.hidden=true;aiPanel.setAttribute('aria-label','AI workflow assistant');
aiPanel.innerHTML=`<div class="assistant-heading"><div><span class="eyebrow">WORKFLOW HELP</span><h2>AI assistant</h2></div><button data-ai-close aria-label="Close AI assistant">×</button></div><p class="assistant-connection" role="status">Checking connection…</p><details class="assistant-connect"><summary>Connect assistant</summary><p>Use this app's server, or a trusted assistant gateway. Provider credentials stay on the server.</p><label>Server URL<input data-ai-server type="url" placeholder="App server (default)" aria-label="Assistant server URL"></label><label>Assistant access token<input data-ai-token type="password" autocomplete="off" aria-label="Assistant access token" placeholder="Separate server token"></label><button data-ai-connect>Connect</button><small>Access tokens last for this session.</small></details><div class="assistant-messages" role="log" aria-label="Conversation"></div><div class="assistant-examples"><button>Help me measure neurites</button><button>How do I review one cell?</button><button>Which preprocessing should I use?</button></div><form class="assistant-composer"><label class="assistant-vision"><input data-ai-vision type="checkbox" checked> Include current view and source image</label><div class="assistant-snapshots" hidden></div><small class="assistant-image-note">On Send, snapshots and image context go to the configured AI provider.</small><label class="assistant-question">Your question<textarea data-ai-question rows="3" maxlength="4000" placeholder="Describe what you want to do…" required></textarea></label><div class="assistant-footer"><button type="button" data-ai-clear>New conversation</button><button data-ai-send type="submit" class="primary">Send</button></div><p class="assistant-error" role="status"></p></form>`;
document.body.append(aiPanel);
const aiQuery=selector=>aiPanel.querySelector(selector);
aiQuery('[data-ai-server]').value=fieldAssistant.endpoint;
function aiError(message){aiQuery('.assistant-error').textContent=message}
function aiContext(){const r=runMeta();return {dataset:state.dataset,name:state.meta.name,shape:state.meta.shape,calibrated:state.meta.calibrated,spacing_xyz:state.meta.spacing,channels:state.meta.channels.map((name,i)=>({index:i,source_name:name,display_name:channelLabel(i),purpose:channelSettings()[i].role})),active_channel:state.channel,z_zero_based:state.z,workspace:state.tab,view:state.mode,projection:state.projection,visible_channels:displayChannels(),recipe:{...state.recipe},region:typeof expRegion==='function'?expRegion().bounds:null,run:r?{id:r.id,method:r.method,objects:r.objects,scope:r.scope,region_bounds:r.region_bounds,factor:r.factor}:null,selected_candidate:state.focusObject?.id||reviewState.data?.object?.id||null}}
function aiResize(image){const canvas=document.createElement('canvas'),scale=Math.min(1,1024/Math.max(image.width,image.height));canvas.width=Math.max(1,Math.round(image.width*scale));canvas.height=Math.max(1,Math.round(image.height*scale));canvas.getContext('2d').drawImage(image,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/png')}
async function aiSnapshot(){const context=aiContext(),images=[],labels=[];if(aiQuery('[data-ai-vision]').checked){if(state.tab==='Review'&&$('#main-host').classList.contains('review-loading'))throw Error('Wait for the review planes to finish loading, then send again.');const shown=state.tab==='Review'?document.querySelector('.review-plane[data-axis=xy] canvas'):state.tab==='Process'?document.querySelector('.preview-grid img[data-plane=labels]')||currentCanvas():currentCanvas();if(shown?.width&&shown?.height){if(shown instanceof HTMLImageElement)await shown.decode();images.push(aiResize(shown));labels.push(state.tab==='Review'?'Result XY inspection':state.tab==='Process'&&shown instanceof HTMLImageElement?'Unsaved crop candidate outlines':'Current displayed view');if(state.tab==='Process'&&shown instanceof HTMLImageElement){const preview=experiment.previews.get(expKey())?.data;context.preview_snapshot=preview?{method:preview.parameters.method,bounds:preview.bounds,factor:preview.factor,z_zero_based:Number(document.querySelector('[aria-label="Preview Z plane"]').value)+preview.bounds[2],channel:preview.channel}:null}}
 const rawZ=context.preview_snapshot?.z_zero_based??context.z_zero_based;const projected=context.workspace!=='Review'&&!(context.workspace==='Process'&&expParams().scope!=='projection')&&context.view==='projection';context.raw_snapshot={view:projected?'projection':'slice',z_zero_based:rawZ};const raw=await bitmap('/api/image?'+query({dataset:context.dataset,channel:context.active_channel,z:rawZ,view:projected?'projection':'slice',projection:context.projection}));images.push(aiResize(raw));labels.push('Raw C'+(context.active_channel+1)+' · '+(projected?context.projection+' projection':'Z '+(rawZ+1)));}
 if(context.dataset!==state.dataset||context.active_channel!==state.channel||context.z_zero_based!==state.z)throw Error('The image changed while capturing. Send again to attach the new view.');context.snapshot_images=labels;return {context,images,labels};}
function aiShowSnapshots(snapshot){const host=aiQuery('.assistant-snapshots');host.replaceChildren();host.hidden=!snapshot.images.length;for(let i=0;i<snapshot.images.length;i++){const figure=document.createElement('figure'),img=document.createElement('img'),caption=document.createElement('figcaption');img.src=snapshot.images[i];img.alt=snapshot.labels[i];caption.textContent=snapshot.labels[i];figure.append(img,caption);host.append(figure)}}
async function aiRequest(path,body){const external=!!fieldAssistant.endpoint;const url=external?fieldAssistant.endpoint.replace(/\/$/,'')+'/api/assistant/'+path:'/api/assistant/'+path;const send=external&&typeof nativeFetch==='function'?nativeFetch:window.fetch.bind(window);const headers={'X-Studio-Request':'1'};if(body)headers['Content-Type']='application/json';if(fieldAssistant.token)headers.Authorization='Bearer '+fieldAssistant.token;const response=await send(url,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(65000)});let result;try{result=await response.json()}catch{throw Error('This URL is not an assistant server.')};if(!response.ok)throw Error(result.error||'Assistant request failed');return result;}
async function aiConnect(){fieldAssistant.config=null;aiQuery('[data-ai-send]').disabled=true;aiQuery('.assistant-connection').textContent='Checking connection…';try{const config=await aiRequest('config');const needsToken=config.enabled&&config.authentication_required&&!fieldAssistant.token;fieldAssistant.config={...config,enabled:config.enabled&&!needsToken};aiQuery('.assistant-connection').textContent=needsToken?'Server ready · enter the assistant access token':config.enabled?'Connected · '+config.model+' · images supported':'Integration ready · configure a provider on the server';aiQuery('[data-ai-send]').disabled=!fieldAssistant.config.enabled;aiQuery('.assistant-connect').open=!fieldAssistant.config.enabled;}catch(error){aiQuery('.assistant-connection').textContent='Assistant is not connected';aiError(error.message);aiQuery('.assistant-connect').open=true;}}
aiButton.onclick=async()=>{aiPanel.hidden=!aiPanel.hidden;aiButton.setAttribute('aria-expanded',String(!aiPanel.hidden));if(!aiPanel.hidden){aiError('');await aiConnect();aiQuery('[data-ai-question]').focus();}};
aiQuery('[data-ai-close]').onclick=()=>{aiPanel.hidden=true;aiButton.setAttribute('aria-expanded','false');aiButton.focus()};
aiQuery('[data-ai-connect]').onclick=async()=>{aiError('');const value=aiQuery('[data-ai-server]').value.trim().replace(/\/$/,'');if(value){try{const u=new URL(value);if((u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))||u.username||u.password||u.search||u.hash||u.pathname!=='/')throw Error();}catch{aiError('Use a trusted HTTPS server origin or a localhost URL.');return}}fieldAssistant.endpoint=value;fieldAssistant.token=aiQuery('[data-ai-token]').value;localStorage.setItem('field-assistant-server',value);await aiConnect()};
for(const button of aiPanel.querySelectorAll('.assistant-examples button'))button.onclick=()=>{aiQuery('[data-ai-question]').value=button.textContent;aiQuery('[data-ai-question]').focus()};
aiQuery('[data-ai-clear]').onclick=()=>{if(fieldAssistant.busy)return;fieldAssistant.history=[];aiQuery('.assistant-messages').replaceChildren();aiQuery('.assistant-snapshots').replaceChildren();aiQuery('.assistant-snapshots').hidden=true;aiError('')};
function aiMessage(role,text){const node=document.createElement('article');node.className='assistant-message '+role;const label=document.createElement('strong');label.textContent=role==='user'?'You':'Assistant';const p=document.createElement('p');p.textContent=text;node.append(label,p);aiQuery('.assistant-messages').append(node);node.scrollIntoView({block:'nearest'});return node}
function aiPlan(result,snapshot,node){if(!result.plan)return;const plan=result.plan,card=document.createElement('div');card.className='assistant-plan';const heading=document.createElement('strong');heading.textContent='Suggested draft';const list=document.createElement('dl');const labels={channel:'Channel',method:'Algorithm',scope:'Scope',factor:'XY reduction',normalize:'Normalize',run_region:'Region',sigma:'Smooth σ (grid px)',background:'Background σ (grid px)',threshold:'Threshold multiplier',min_size:'Minimum pixels / voxels',distance:'Seed distance (grid units)',bounds:'Native region'};for(const [key,value] of Object.entries(plan)){if(value===null||key==='workspace')continue;const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=labels[key]||key;dd.textContent=key==='channel'?'C'+(value+1)+' · '+channelLabel(value):key==='method'?(methodInfo[value]?.[0]||value):key==='factor'?value+'×':key==='run_region'?(value==='all'?'Full image':'Selected region'):Array.isArray(value)?value.join(', '):String(value);list.append(dt,dd)}const button=document.createElement('button');button.textContent=list.children.length?'Apply draft · '+plan.workspace:'Open '+plan.workspace;button.onclick=async()=>{try{if(snapshot.context.dataset!==state.dataset)throw Error('Open the original image before applying this suggestion.');if(!(await resolveDrawing()))return;if(plan.channel!==null){channelSettings()[plan.channel].included=true;channelSettings()[plan.channel].visible=true;refreshChannelPicker();$('#channel').value=plan.channel;await $('#channel').onchange({target:$('#channel')})}for(const key of ['method','scope','factor','normalize','sigma','background','threshold','min_size','distance','run_region'])if(plan[key]!==null)state.recipe[key]=plan[key];if(['sigma','background','min_size','distance'].some(key=>plan[key]!==null))state.recipe.units='grid';if(plan.run_region==='all'){delete state.recipe.bounds;delete state.recipe.region_margin}if(plan.run_region==='selected')state.recipe.scope='volume';if(plan.bounds){experiment.regions.set(expKey(),{bounds:[...plan.bounds],margin:16});state.recipe.run_region='selected';state.recipe.bounds=[...plan.bounds];state.recipe.region_margin=16;state.recipe.scope='volume'}state.tab=plan.workspace;renderLayout();button.disabled=true;button.textContent='Draft applied';status('Assistant draft applied · preview it before running');}catch(error){aiError(error.message)}};card.append(heading,list,button);node.append(card)}
aiQuery('.assistant-composer').onsubmit=async event=>{event.preventDefault();if(fieldAssistant.busy||!fieldAssistant.config?.enabled)return;const input=aiQuery('[data-ai-question]'),message=input.value.trim();if(!message)return;fieldAssistant.busy=true;aiError('');const send=aiQuery('[data-ai-send]');send.disabled=true;send.textContent='Reading…';try{const snapshot=await aiSnapshot();aiShowSnapshots(snapshot);aiMessage('user',message);input.value='';const result=await aiRequest('chat',{message,history:fieldAssistant.history.slice(-10),context:snapshot.context,images:snapshot.images});const node=aiMessage('assistant',result.answer);aiPlan(result,snapshot,node);fieldAssistant.history.push({role:'user',text:message},{role:'assistant',text:result.answer});fieldAssistant.history=fieldAssistant.history.slice(-10);}catch(error){aiError(error.message);if(!input.value)input.value=message}finally{fieldAssistant.busy=false;send.disabled=!fieldAssistant.config?.enabled;send.textContent='Send'}};
aiPanel.addEventListener('keydown',event=>{if(event.key==='Escape'){aiQuery('[data-ai-close]').click();event.stopPropagation()}if(event.key==='Enter'&&(event.ctrlKey||event.metaKey)&&event.target.matches('textarea'))aiQuery('.assistant-composer').requestSubmit()});
