'use strict';
// Shared accessible modal: native focus trap, Escape cancellation, explicit actions.
function fieldDialog({title,message,actions}){return new Promise(resolve=>{if(document.querySelector('.field-dialog[open]')){resolve('cancel');return}const previous=document.activeElement,dialog=document.createElement('dialog');dialog.className='field-dialog';const heading=document.createElement('h2');heading.id='field-dialog-title';heading.textContent=title;dialog.setAttribute('aria-labelledby',heading.id);const text=document.createElement('p');text.textContent=message;const buttons=document.createElement('div');buttons.className='dialog-actions';const finish=value=>{dialog.close();dialog.remove();if(previous?.isConnected)previous.focus({preventScroll:true});resolve(value)};for(const action of actions){const button=document.createElement('button');button.textContent=action.label;if(action.primary)button.className='primary';if(action.danger)button.className='danger';button.disabled=!!action.disabled;button.onclick=()=>finish(action.value);buttons.append(button)}dialog.append(heading,text,buttons);dialog.addEventListener('cancel',event=>{event.preventDefault();finish('cancel')});document.body.append(dialog);dialog.showModal();buttons.querySelector('button:not(:disabled)')?.focus()})}
async function resolveDrawing(){if(!state.pending.length)return true;const minimum=['polygon','freehand'].includes(state.tool)?3:state.tool==='point'?1:2;const result=await fieldDialog({title:'Finish this drawing first',message:'You have '+state.pending.length+' points in an unfinished drawing. Keep drawing, add it to your annotations, or discard only this draft.',actions:[{label:'Keep drawing',value:'cancel'},{label:'Discard draft',value:'discard',danger:true},{label:'Finish drawing',value:'finish',primary:true,disabled:state.pending.length<minimum}]});if(result==='cancel')return false;if(result==='finish')finishDrawing();else{cancelDraft();scheduleDraw()}return !state.pending.length}
async function confirmRemoval(){return await fieldDialog({title:'Delete annotation?',message:'This removes this mark from this workspace. You can undo the deletion until you reload the page.',actions:[{label:'Keep annotation',value:'cancel'},{label:'Delete annotation',value:'delete',danger:true}]})==='delete'}
const dialogSetTool=setTool;setTool=async function(tool){if(tool!==state.tool&&!(await resolveDrawing()))return;dialogSetTool(tool)};
const dialogRemove=removeSelected;removeSelected=async function(){if(state.selected&&await confirmRemoval())dialogRemove()};
// Keep keyboard shortcuts from altering the canvas while a modal has focus.
window.addEventListener('keydown',event=>{if(document.querySelector('dialog[open]'))event.stopImmediatePropagation()},true);
function annotationGuide(){return fieldDialog({title:'What would you like to annotate?',message:'Work on the 2D image for precise marks. Point: click once per cell. Outline: click around a cell, then Finish. Neurite: click along a branch, then Finish. Hold Space and drag to pan; scroll to zoom. Processing and marks use the active channel.',actions:[{label:'Close',value:'cancel'},{label:'Count cells',value:'point',primary:true},{label:'Trace neurites',value:'polyline'},{label:'Outline cells',value:'polygon'}]}).then(async tool=>{if(tool==='cancel')return;if(!(await resolveDrawing()))return;state.annotationView='slice';renderLayout();setTool(tool)})}
const dialogLayout=renderLayout;renderLayout=function(){dialogLayout();if(typeof refreshLayerControls==='function')refreshLayerControls();if(state.tab==='Annotate'){const head=document.querySelector('.annotation-head');if(head&&!head.querySelector('.annotation-guide')){const guide=document.createElement('button');guide.className='annotation-guide';guide.textContent='Choose a tool / How to annotate';guide.onclick=annotationGuide;head.append(guide)}document.querySelectorAll('.annotation-view-choice button').forEach(button=>{const action=button.onclick;button.onclick=async()=>{if(await resolveDrawing())action()}});document.querySelectorAll('[data-reload]').forEach(button=>{button.onclick=safe(async()=>{if(!(await resolveDrawing()))return;const answer=await fieldDialog({title:'Reload saved annotations?',message:'Reload the latest saved revision. Any finished edits that have not saved yet will be replaced.',actions:[{label:'Keep working',value:'cancel'},{label:'Reload saved',value:'reload',primary:true}]});if(answer==='reload'){await loadAnnotations();updateAnnotationPanels();scheduleDraw()}})})}};
const dialogList=fillAnnotationList;fillAnnotationList=function(el){dialogList(el);el.querySelectorAll('button').forEach(button=>{const action=button.onclick;if(button.textContent==='Delete')button.onclick=async()=>{if(await confirmRemoval())action()};if(button.textContent==='Show')button.onclick=async()=>{if(await resolveDrawing())action()}})};
for(const button of document.querySelectorAll('[data-tab]')){const action=button.onclick;button.onclick=async()=>{if(!(await resolveDrawing()))return;const entering=button.dataset.tab==='Annotate'&&state.tab!=='Annotate';action();if(entering){state.annotationView='slice';state.tool='point';renderLayout();setTool('point');status('Point tool ready • click a cell to mark it. Choose Neurite or Outline for paths and boundaries.')}}}
const oldChannelChange=$('#channel').onchange;$('#channel').onchange=async event=>{const next=event.target.value;event.target.value=state.channel;if(!(await resolveDrawing()))return;event.target.value=next;oldChannelChange(event)};
const oldDepthInput=$('#z').oninput;$('#z').oninput=async event=>{const next=event.target.value;event.target.value=state.z;if(!(await resolveDrawing()))return;event.target.value=next;oldDepthInput(event)};

const dialogDepth=setDepth;setDepth=async function(z){if(state.pending.length)stopDepth();if(await resolveDrawing())dialogDepth(z)};
const dialogDataset=selectDataset;selectDataset=async function(key){if(!(await resolveDrawing())){$('#dataset').value=state.dataset;return}return dialogDataset(key)};
