'use strict';
// Explore display tools. View state never changes source voxels or segmentation runs.
const projectionControl=document.createElement('label');projectionControl.className='explore-projection';projectionControl.title='Collapse the acquired Z planes for display';projectionControl.textContent='Z method ';const projectionSelect=document.createElement('select');projectionSelect.setAttribute('aria-label','Z projection method');for(const [value,label] of [['max','Maximum'],['mean','Average'],['sum','Sum']])projectionSelect.add(new Option(label,value));projectionSelect.value=state.projection;projectionSelect.onchange=()=>{state.projection=projectionSelect.value;scheduleDraw()};projectionControl.append(projectionSelect);$('#simple-toolbar').append(projectionControl);
// View tools live in their own labeled group beside the context line, so the data toolbar keeps one row and image space stays tall.
function viewIcon(name){const paths={ruler:'M3 17 17 3l4 4L7 21ZM7.5 12.5l2 2M10.5 9.5l2 2M13.5 6.5l2 2',grid:'M4 4h16v16H4ZM4 9.3h16M4 14.7h16M9.3 4v16M14.7 4v16',scale:'M3 15h18M3 11v8M21 11v8M12 13v4',region:'M12 3 20 7.5v9L12 21 4 16.5v-9ZM4 7.5 12 12l8-4.5M12 12v9',full:'M4 9V4h5M20 9V4h-5M4 15v5h5M20 15v5h-5',save:'M12 4v11M7 10l5 5 5-5M5 20h14'};return '<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>'}
const viewRow=document.createElement('div');viewRow.className='context-row';contextLine.before(viewRow);
const viewTools=document.createElement('div');viewTools.className='view-tools';viewTools.setAttribute('role','group');viewTools.setAttribute('aria-label','View tools');viewRow.append(contextLine,viewTools);new MutationObserver(()=>{contextLine.title=contextLine.textContent}).observe(contextLine,{childList:true,characterData:true,subtree:true});
const regionButton=document.createElement('button');regionButton.className='explore-tool-button tool-group-start';regionButton.innerHTML=viewIcon('region')+'<span class="explore-tool-label">3D region</span>';regionButton.setAttribute('aria-label','Choose 3D region');regionButton.title='Choose native X, Y, and Z limits for a focused 3D view';regionButton.onclick=openRegionDialog;viewTools.append(regionButton);
const resetRegionButton=document.createElement('button');resetRegionButton.className='explore-tool-button';resetRegionButton.innerHTML=viewIcon('full')+'<span class="explore-tool-label">Full field</span>';resetRegionButton.setAttribute('aria-label','Return to full field');resetRegionButton.title='Return to the full 3D image';resetRegionButton.onclick=()=>{state.region3d=null;state.focusObject=null;scheduleDraw();resetRegionButton.hidden=true};resetRegionButton.hidden=true;viewTools.append(resetRegionButton);
const exportViewButton=document.createElement('button');exportViewButton.className='explore-tool-button tool-group-start save-view';exportViewButton.innerHTML=viewIcon('save')+'<span class="explore-tool-label">Save view</span>';exportViewButton.setAttribute('aria-label','Save view as PNG');exportViewButton.title='Download the current image viewport as a PNG, including display colors and overlays';exportViewButton.onclick=()=>{const canvases=[...document.querySelectorAll('#main-host .viewport canvas')];if(!canvases.length)return status('Open an image view before exporting',true);const target=canvases[canvases.length-1];target.toBlob(blob=>{if(!blob)return status('Could not export this view',true);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`field-${state.dataset}-${state.mode}-${new Date().toISOString().replace(/[:.]/g,'-')}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Current image viewport saved as PNG')},'image/png')};viewTools.append(exportViewButton);
function openRegionDialog(){if(!state.meta)return;const [nz,,ny,nx]=state.meta.shape;let preset=[0,0,0,nx,ny,nz];const v=$('#main-host .viewport[data-kind="projection"],#main-host .viewport[data-kind="slice"]');if(v?.transform){const t=v.transform,c=v.querySelector('canvas');preset=[Math.max(0,Math.floor(-t.ox/t.s)),Math.max(0,Math.floor(-t.oy/t.s)),0,Math.min(nx,Math.ceil((c.clientWidth-t.ox)/t.s)),Math.min(ny,Math.ceil((c.clientHeight-t.oy)/t.s)),nz];if(preset[3]<=preset[0]||preset[4]<=preset[1])preset=[0,0,0,nx,ny,nz]}
 const dialog=document.createElement('dialog');dialog.className='region-dialog';const form=document.createElement('form');form.method='dialog';const title=document.createElement('h2');title.textContent='3D region';const note=document.createElement('p');note.textContent='Native pixel bounds. End values are exclusive; Z covers acquired planes. The current 2D viewport sets the initial XY region.';form.append(title,note);const fields=document.createElement('div');fields.className='region-fields';for(const [axis,i,max] of [['X',0,nx],['Y',1,ny],['Z',2,nz]]){for(const [end,offset] of [['Start',0],['End',3]]){const label=document.createElement('label');label.textContent=axis+' '+end;const input=document.createElement('input');input.type='number';input.min=end==='Start'?0:1;input.max=max;input.step=1;input.required=true;input.name=axis.toLowerCase()+(end==='Start'?'0':'1');input.value=preset[i+offset];label.append(input);fields.append(label)}}form.append(fields);const error=document.createElement('p');error.role='status';error.className='error';form.append(error);const actions=document.createElement('div');actions.className='buttons';const cancel=document.createElement('button');cancel.type='button';cancel.textContent='Cancel';cancel.onclick=()=>dialog.close();const apply=document.createElement('button');apply.type='submit';apply.textContent='Open region in 3D';actions.append(cancel,apply);form.append(actions);form.onsubmit=e=>{e.preventDefault();const f=new FormData(form),values=['x0','y0','z0','x1','y1','z1'].map(k=>Number(f.get(k)));if(values.some(v=>!Number.isInteger(v))||values.some((v,i)=>v<(i<3?0:1)||v>(i===0||i===3?nx:i===1||i===4?ny:nz))||[0,1,2].some(i=>values[i]>=values[i+3])){error.textContent='Enter increasing X, Y, Z bounds within this image.';return}state.region3d=values;state.focusObject=null;state.mode='volume';dialog.close();renderLayout()};dialog.append(form);document.body.append(dialog);dialog.addEventListener('close',()=>dialog.remove());dialog.showModal()}
function openIsolatedCell(obj){if(!obj||!state.run)return;pointCache.clear();atlasCache.clear();imageCache.clear();state.focusObject={run:state.run,id:obj.id};state.region3d=null;state.compare=false;state.mode='volume';state.tab='Explore';renderLayout();status('Showing candidate #'+obj.id+' inside its current corrected 3D mask')}
const previousInspector=showObjectInspector;showObjectInspector=function(data){previousInspector(data);if(data?.object&&measurementEligible()){const button=document.createElement('button');button.textContent='◉ Open cell in 3D';button.title='Show only this candidate’s current corrected 3D mask with source signal';button.onclick=()=>openIsolatedCell(data.object);$('#object-inspector h3')?.after(button)}};
const previousExploreLayout=renderLayout;renderLayout=function(){previousExploreLayout();projectionControl.hidden=state.tab!=='Explore'||state.mode!=='projection';regionButton.hidden=state.tab!=='Explore';exportViewButton.hidden=state.tab!=='Explore';resetRegionButton.hidden=state.tab!=='Explore'||(!state.region3d&&!state.focusObject);viewTools.hidden=state.tab!=='Explore'};
