'use strict';
// Review decisions and label corrections are separate from immutable algorithm output.
const measurementState={serial:0,offset:0,filters:{status:'all',boundary:'all',sort:'id',search:''},host:null,data:null};
const decisionNames={unreviewed:'Unreviewed',accepted:'Accepted',rejected:'Rejected',needs_review:'Needs review'};
function measurementContext(){return {dataset:state.dataset,channel:state.channel,run:state.run}}
function measurementEligible(){const r=runMeta();return r&&!r.historical&&r.scope==='volume'&&r.method!=='preprocess'}
function measurementQuery(){return {...measurementContext(),...measurementState.filters,offset:measurementState.offset,limit:50}}
function measurementSame(q){return state.tab==='Review'&&q.dataset===state.dataset&&q.channel===state.channel&&q.run===state.run}
function measurementBadge(status){const b=expNode('span','decision-badge '+status,decisionNames[status]);return b}

const measurementReviewLayout=renderReviewWorkspace;
renderReviewWorkspace=function(){measurementReviewLayout();measurementState.serial++;measurementState.offset=0;measurementState.data=null;if(!measurementEligible())return;
 const host=expNode('section','measurement-panel');host.setAttribute('aria-label','Candidate measurements');measurementState.host=host;
 const header=expNode('div','measurement-heading');header.append(expNode('h2','','Candidate review & measurements'));const filterButton=expButton('⚑ Filters','measurement-filter-button',()=>{const d=expModal('Filter candidates','Choose which algorithm candidates appear in the review queue.','measurement-filter-dialog');controls.hidden=false;d.append(controls);const actions=expNode('div','dialog-actions');actions.append(expButton('Done','primary',()=>d.close()));d.append(actions);d.addEventListener('close',()=>{controls.hidden=true;if(host.isConnected)host.querySelector('.measurement-heading').after(controls)})});filterButton.title='Filter by decision, boundary contact, size order, or candidate ID';header.append(filterButton,expButton('⚙ Count rules','exp-secondary',openCountProtocol),expButton('✎ Correct mask','correction-open',()=>openCorrection(reviewState.data?.object)),expButton('Export ↗','exp-secondary',openMeasurementExport));host.append(header);
 const controls=expNode('div','measurement-filters');controls.hidden=true;
 for(const [key,label,choices] of [['status','Review status',[['all','All decisions'],...Object.entries(decisionNames)]],['boundary','Boundary policy',[['all','Include all edges'],['interior','Exclude edge contacts'],['edge','Edge contacts only']]],['sort','Sort candidates',[['id','Candidate ID'],['size_desc','Largest first'],['size_asc','Smallest first']]]]){
  const l=expNode('label','',label),select=document.createElement('select');select.setAttribute('aria-label',label);choices.forEach(([v,t])=>select.add(new Option(t,v)));select.value=measurementState.filters[key];select.onchange=()=>{measurementState.filters[key]=select.value;measurementState.offset=0;filterButton.classList.toggle('active',Object.values(measurementState.filters).some(v=>!['all','id',''].includes(v)));loadMeasurements()};l.append(select);controls.append(l);
 }
 const l=expNode('label','','Candidate ID'),search=document.createElement('input');search.type='search';search.placeholder='Exact ID';search.setAttribute('aria-label','Find candidate ID');search.value=measurementState.filters.search;let timer;search.oninput=()=>{measurementState.serial++;clearTimeout(timer);measurementState.filters.search=search.value;measurementState.offset=0;filterButton.classList.toggle('active',Object.values(measurementState.filters).some(v=>!['all','id',''].includes(v)));timer=setTimeout(loadMeasurements,200)};l.append(search);controls.append(l);host.append(controls);filterButton.classList.toggle('active',Object.values(measurementState.filters).some(v=>!['all','id',''].includes(v)));
 const countCard=expNode('div','count-card','Loading count review…');countCard.role='status';host.append(countCard);
 const summary=expNode('p','measurement-summary','Loading candidates…');summary.role='status';host.append(summary);host.append(expNode('div','measurement-table-wrap'));host.append(expNode('div','measurement-pagination'));$('#main-host').append(host);const jump=expButton('Candidates ↓','measurement-jump',()=>host.scrollIntoView({block:'start'}));$('#main-host .review-controls').append(jump);loadMeasurements();
};

async function loadMeasurements(){
 const host=measurementState.host;if(!host?.isConnected||!measurementEligible()||state.tab!=='Review')return;
 const q=measurementQuery(),serial=++measurementState.serial;host.classList.add('pending');
 try{const data=await api('/api/measurements?'+query(q));if(serial!==measurementState.serial||!host.isConnected||!measurementSame(q))return;measurementState.data=data;measurementState.offset=data.offset;
  renderCountCard(host.querySelector('.count-card'),data);
  const jump=$('#main-host .measurement-jump');if(jump){jump.textContent=data.count.ready?`✓ Reviewed count ${data.count.reviewed_count} ↓`:`◌ ${data.count.unresolved} to review ↓`;jump.title=data.count.ready?'Completed reviewer decisions; inspect count rules and export below':'Open candidate queue and review unresolved objects'}
  host.querySelector('.measurement-summary').textContent=data.matched.toLocaleString()+' / '+data.total.toLocaleString()+' current candidates · '+data.counts.accepted+' accepted · '+data.counts.needs_review+' need review · '+data.counts.rejected+' rejected. Selection: median '+(data.summary.median_voxels??'—')+' grid voxels; '+data.summary.edge_count+' touch a volume edge.';
  const wrap=host.querySelector('.measurement-table-wrap');wrap.replaceChildren();const table=expNode('table','measurement-table');table.setAttribute('aria-label','Candidate measurements table');const head=expNode('thead'),tr=expNode('tr');['Candidate','Decision','Grid voxels','Volume (µm³)','Volume edges'].forEach(t=>tr.append(expNode('th','',t)));head.append(tr);table.append(head);const body=expNode('tbody');
  for(const o of data.rows){const row=expNode('tr');row.dataset.object=o.id;const id=expNode('td');id.append(expButton('#'+o.id,'candidate-locate',()=>locateMeasurement(o.id)));row.append(id);const status=expNode('td');status.append(measurementBadge(o.status));row.append(status,expNode('td','',o.voxels.toLocaleString()),expNode('td','',o.volume_um3===null?'Uncalibrated':o.volume_um3.toLocaleString(undefined,{maximumFractionDigits:2})),expNode('td','',o.boundary_faces.join(', ')||'None'));body.append(row)}table.append(body);wrap.append(table);if(!data.rows.length)wrap.append(expNode('p','measurement-empty','No candidates match. Change the decision, edge or ID filter.'));
  const pagination=host.querySelector('.measurement-pagination');pagination.replaceChildren();const prev=expButton('← Previous','',()=>{measurementState.offset=Math.max(0,measurementState.offset-50);loadMeasurements()}),next=expButton('Next →','',()=>{measurementState.offset+=50;loadMeasurements()});prev.disabled=!data.offset;next.disabled=data.offset+data.rows.length>=data.matched;pagination.append(prev,expNode('span','',data.matched?`${data.offset+1}–${data.offset+data.rows.length} of ${data.matched}`:'0 candidates'),next);highlightMeasurement();
 }catch(e){if(serial===measurementState.serial&&host.isConnected){measurementState.data=null;host.querySelector('.measurement-summary').textContent=e.message;host.querySelector('.measurement-table-wrap').replaceChildren();host.querySelector('.measurement-pagination').replaceChildren()}}
 finally{if(serial===measurementState.serial)host.classList.remove('pending')}
}
let measurementLocateSerial=0;
async function locateMeasurement(id){const q={...measurementContext(),object:id},serial=++measurementLocateSerial;try{const data=await api('/api/object-location?'+query(q));if(serial!==measurementLocateSerial||!measurementSame(q))return;[reviewState.x,reviewState.y,state.z]=data.cursor;clampReviewCursor();scheduleReview();$('#desk').scrollTop=0;$('#task-panel').scrollTop=0;}catch(e){expNotice(e.message,'warning')}}
function highlightMeasurement(){const id=reviewState.data?.object?.id;measurementState.host?.querySelectorAll('tr[data-object]').forEach(row=>{row.classList.toggle('selected',Number(row.dataset.object)===id);row.querySelector('button').setAttribute('aria-pressed',String(Number(row.dataset.object)===id))})}
function renderCountCard(card,data){
 const c=data.count,protocol=data.protocol,method=runMeta()?.method;
 card.classList.toggle('ready',c.ready);card.replaceChildren();
 const mark=expNode('span','count-card-icon',c.ready?'✓':'◌');const textBox=expNode('div');
 textBox.append(expNode('strong','',c.ready?`${c.reviewed_count} reviewed ${c.target}`:`${c.accepted_so_far} accepted so far · ${c.unresolved} unresolved`));
 let detail=protocol.revision?`${c.target} · ${c.channel_role} · ${c.edge_policy==='exclude'?'edge objects excluded':'edge objects included'}`:'Set a count target, channel meaning and edge rule to finish a reviewed count.';
 if(method==='sato')detail='Sato labels are connected networks. They cannot be reported as cell or neuron counts.';
 textBox.append(expNode('small','',detail));card.append(mark,textBox);
 const revision=data.label_revision?'Corrected mask '+data.label_revision.slice(0,8):'Original algorithm mask';
 card.append(expNode('span','count-card-revision',revision));
}
const measurementInspector=showObjectInspector;
showObjectInspector=function(data){measurementInspector(data);highlightMeasurement();if(!measurementEligible())return;const box=$('#object-inspector');if(data.object){box.querySelector('h3').after(expButton('Review candidate #'+data.object.id,'review-decision-button',()=>openCandidateDecision(data.object)),expButton('✎ Fix this mask','correction-inspector-button',()=>openCorrection(data.object)));if(data.object.note)box.append(expNode('p','candidate-note',data.object.note));}else box.querySelector('h3').after(expButton('＋ Add object here','correction-inspector-button',()=>openCorrection(null)));};

function openCandidateDecision(obj){
 const q=measurementContext(),d=expModal('Review candidate #'+obj.id,'Accept or reject the current mask after inspecting XY, XZ and YZ. A decision is invalidated if this object is later corrected.','decision-dialog');
 const body=expNode('div','decision-form'),l=expNode('label','exp-field','Decision'),select=document.createElement('select');select.setAttribute('aria-label','Candidate decision');Object.entries(decisionNames).forEach(([v,t])=>select.add(new Option(t,v)));select.value=obj.status;l.append(select);body.append(l);
 const nl=expNode('label','exp-field','Review note'),note=document.createElement('textarea');note.maxLength=2000;note.rows=4;note.value=obj.note||'';note.setAttribute('aria-label','Candidate review note');nl.append(note);body.append(nl,expNode('p','',obj.boundary_faces.length?'Edge flags: '+obj.boundary_faces.join(', '):'No processed-volume edge contact.'));d.append(body);
 const message=expNode('p','decision-message');message.role='status';d.append(message);const actions=expNode('footer','decision-actions');const save=expButton('Save decision','exp-run',async()=>{if(!measurementSame(q)){message.textContent='The active run changed. Close and reopen this review.';return}save.disabled=true;message.textContent='Saving decision…';try{await api('/api/object-decision',{...q,object:obj.id,status:select.value,note:note.value,expected_revision:obj.review_revision,expected_label_revision:obj.label_revision});d.close();if(measurementSame(q)){loadMeasurements();reviewState.signature=null;scheduleReview()}expNotice('Candidate #'+obj.id+' · '+decisionNames[select.value]+' saved.')}catch(e){message.textContent=e.message;save.disabled=false;reload.hidden=false}});
 const reload=expButton('Reload latest decision','',async()=>{reload.disabled=true;try{const latest=await api('/api/measurements?'+query({...q,search:obj.id}));if(!d.isConnected)return;const row=latest.rows[0];if(!row)throw Error('Candidate no longer exists. Close and select another.');obj={...obj,...row,review_revision:latest.revision,label_revision:latest.label_revision};select.value=obj.status;note.value=obj.note;message.textContent='Latest decision loaded. Confirm your changes before saving.';reload.hidden=true}catch(e){message.textContent=e.message}finally{reload.disabled=false}});reload.hidden=true;actions.append(reload,expButton('Cancel','',()=>d.close()),save);d.append(actions);
}

function openCountProtocol(){
 const q=measurementContext(),existing=measurementState.data?.protocol||{},d=expModal('Count rules','Define what one count means for this image and run. The result remains a reviewer-assessed candidate count.','decision-dialog');
 const form=expNode('div','decision-form'),targetLabel=expNode('label','exp-field','Count target'),target=document.createElement('input');target.maxLength=100;target.placeholder='e.g. cell bodies or nuclei';target.value=existing.target||'';targetLabel.append(target);
 const channelLabel=expNode('label','exp-field','This channel shows'),channel=document.createElement('input');channel.maxLength=100;channel.placeholder='e.g. DAPI nuclei; confirm from acquisition notes';channel.value=existing.channel_role||'';channelLabel.append(channel);
 const edgeLabel=expNode('label','exp-field','Objects touching the acquired volume edge'),edge=document.createElement('select');edge.add(new Option('Choose an edge rule',''));edge.add(new Option('Include after individual review','include'));edge.add(new Option('Exclude from count','exclude'));edge.value=existing.edge_policy||'';edgeLabel.append(edge);
 const noteLabel=expNode('label','exp-field','Protocol note (optional)'),note=document.createElement('textarea');note.maxLength=1000;note.rows=2;note.value=existing.reviewer_note||'';noteLabel.append(note);form.append(targetLabel,channelLabel,edgeLabel,noteLabel);d.append(form);
 const message=expNode('p','decision-message');message.role='status';d.append(message);const actions=expNode('footer','decision-actions'),save=expButton('Save count rules','exp-run',async()=>{save.disabled=true;try{await api('/api/count-protocol',{...q,target:target.value,channel_role:channel.value,edge_policy:edge.value,reviewer_note:note.value,expected_revision:existing.revision||null});d.close();loadMeasurements();expNotice('Count rules saved. Review every included candidate to complete the count.')}catch(e){message.textContent=e.message;save.disabled=false}});actions.append(expButton('Cancel','',()=>d.close()),save);d.append(actions);
}

function openCorrection(obj){
 const q=measurementContext(),data=measurementState.data,expected=data?.label_revision||null;
 if(!data){expNotice('Load the candidate table before correcting labels.','warning');return}
 const cursor={x:reviewState.x,y:reviewState.y,z:state.z};
 const d=expModal('Correct candidate mask','Preview XY, XZ and YZ before saving. Split uses a straight plane; Add uses an ellipsoid. Check the biological boundary in the source image.','correction-dialog');
 const form=expNode('div','decision-form correction-form');
 const actionLabel=expNode('label','exp-field','Correction'),action=document.createElement('select');
 (obj?[['split','Split at a plane'],['merge','Merge into another ID'],['delete','Delete this mask'],['undo','Undo last correction']]:[['add','Add ellipsoid at cursor'],['undo','Undo last correction']]).forEach(([v,t])=>action.add(new Option(t,v)));actionLabel.append(action);form.append(actionLabel);
 if(obj)form.append(expNode('p','',`Candidate #${obj.id} · ${obj.voxels.toLocaleString()} grid voxels`));
 const axisLabel=expNode('label','exp-field','Split axis'),axis=document.createElement('select');for(const v of ['x','y','z'])axis.add(new Option(v.toUpperCase(),v));axisLabel.append(axis);form.append(axisLabel);
 const coordinateLabel=expNode('label','exp-field','Split at native coordinate'),coordinate=document.createElement('input');coordinate.type='number';coordinate.min=0;coordinate.max=state.meta.shape[3]-1;coordinate.step=1;coordinate.value=cursor.x;coordinateLabel.append(coordinate);form.append(coordinateLabel);
 const targetLabel=expNode('label','exp-field','Merge into candidate ID'),target=document.createElement('input');target.type='number';target.min=1;target.step=1;target.placeholder='Existing ID';targetLabel.append(target);form.append(targetLabel);
 const radiusLabel=expNode('label','exp-field','XY radius (native pixels)'),radius=document.createElement('input');radius.type='number';radius.min=1;radius.max=50;radius.step=.5;radius.value=6;radiusLabel.append(radius);form.append(radiusLabel);
 const zRadiusLabel=expNode('label','exp-field','Z radius (planes)'),zRadius=document.createElement('input');zRadius.type='number';zRadius.min=0;zRadius.max=10;zRadius.step=.5;zRadius.value=state.meta.shape[0]===1?0:1;zRadiusLabel.append(zRadius);form.append(zRadiusLabel);
 const msg=expNode('p','decision-message','Choose an operation, then preview.');msg.role='status';
 const previewArea=expNode('div','correction-preview');d.append(form,msg,previewArea);
 const actions=expNode('footer','decision-actions'),previewButton=expButton('Preview change','',doPreview),apply=expButton('Save correction','exp-run',doApply);apply.disabled=true;actions.append(expButton('Cancel','',()=>d.close()),previewButton,apply);d.append(actions);
 let previewed=null;
 function update(){axisLabel.hidden=coordinateLabel.hidden=action.value!=='split';targetLabel.hidden=action.value!=='merge';radiusLabel.hidden=zRadiusLabel.hidden=action.value!=='add';coordinate.max=state.meta.shape[axis.value==='z'?0:axis.value==='y'?2:3]-1;coordinate.value=cursor[axis.value];previewed=null;apply.disabled=true;previewArea.replaceChildren();msg.textContent='Preview the correction before saving.'}
 for(const input of [action,axis,coordinate,target,radius,zRadius])input.addEventListener(input.tagName==='SELECT'?'change':'input',()=>{if(input===action||input===axis)update();else{previewed=null;apply.disabled=true;previewArea.replaceChildren()}});
 update();
 function payload(){return {...q,action:action.value,object:obj?.id,target:target.value,axis:axis.value,coordinate:coordinate.value,radius_xy:radius.value,radius_z:zRadius.value,...cursor,expected_label_revision:expected}}
 async function doPreview(){previewButton.disabled=true;apply.disabled=true;msg.textContent='Building correction preview…';try{const draft=payload(),result=await api('/api/correction-preview',draft);if(!d.isConnected)return;previewed=draft;msg.textContent=`${result.description} · ${result.affected_voxels.toLocaleString()} voxels change · ${result.candidate_count} candidates after`;previewArea.replaceChildren();for(const [axisName,png] of Object.entries(result.planes)){const figure=expNode('figure'),image=document.createElement('img');image.src='data:image/png;base64,'+png;image.alt=axisName.toUpperCase()+' corrected label preview';figure.append(image,expNode('figcaption','',axisName.toUpperCase()));previewArea.append(figure)}apply.disabled=false}catch(e){msg.textContent=e.message}finally{previewButton.disabled=false}}
 async function doApply(){if(!previewed||!measurementSame(q))return;apply.disabled=true;try{const result=await api('/api/correction-save',previewed);d.close();if(measurementSame(q)){reviewState.signature=null;reviewState.data=null;loadMeasurements();scheduleReview();scheduleDraw()}expNotice(result.description+' saved as '+result.label_revision.slice(0,8)+'. Changed IDs need a fresh decision.')}catch(e){msg.textContent=e.message;previewed=null}}
}

async function downloadMeasurement(path,name){
 const response=await fetch(path);if(!response.ok){const err=await response.json();throw Error(err.error)}
 const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=name;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);
}

async function openMeasurementExport(){
 const q={...measurementContext(),...measurementState.filters},d=expModal('Export review','Download corrected labels, the full count summary, or a filtered candidate table. Each export pins the same revisions.','measurement-export');
 const info=expNode('div','export-preview');info.role='status';info.textContent='Preparing export preview…';d.append(info);
 const actions=expNode('footer','decision-actions');
 function downloadButton(label,path,name){const button=expButton(label,'exp-run',async()=>{button.disabled=true;try{await downloadMeasurement(path()+query(q),name());expNotice(label+' downloaded.')}catch(e){info.textContent=e.message;refresh.hidden=false}finally{button.disabled=false}});button.disabled=true;return button}
 const csv=downloadButton('Candidate CSV',()=>'/api/measurements.csv?',()=>`candidates-${q.run.slice(0,8)}-${q.status}.csv`);
 const summary=downloadButton('Count JSON',()=>'/api/count-summary.json?',()=>`count-${q.run.slice(0,8)}.json`);
 const mask=downloadButton('Corrected TIFF',()=>'/api/result-file?kind=corrected-labels&',()=>`corrected-labels-${q.run.slice(0,8)}.tif`);
 const refresh=expButton('Refresh preview','',prepare);refresh.hidden=true;actions.append(refresh,expButton('Close','',()=>d.close()),csv,summary,mask);d.append(actions);
 async function prepare(){for(const b of [csv,summary,mask])b.disabled=true;try{const data=await api('/api/measurements?'+query({...q,limit:5}));if(!d.isConnected)return;q.revision=data.revision||'';q.label_revision=data.label_revision||'';q.protocol_revision=data.protocol_revision||'';info.replaceChildren(expNode('h3','',data.count.ready?`${data.count.reviewed_count} reviewed ${data.count.target}`:`${data.count.accepted_so_far} accepted so far; ${data.count.unresolved} unresolved`),expNode('p','','Original algorithm: '+runMeta().objects+' candidates · Current mask: '+data.total+' candidates · '+(data.label_revision?'corrected revision '+data.label_revision:'original labels')),expNode('p','','CSV selection: '+data.matched+' candidates · '+(decisionNames[q.status]||'all decisions')+' · '+q.boundary+' edges'),expNode('p','','Count rules: '+(data.protocol_revision?`${data.count.target} / ${data.count.channel_role} / ${data.count.edge_policy} edges`:'Not set')),expNode('p','','Review revision: '+(data.revision||'No decisions yet')+' · source '+q.dataset+' · C'+(q.channel+1)));if(!data.count.ready)info.append(expNode('p','export-warning',(data.protocol_revision?'Review every included candidate before reporting this count.':'Set count rules and review every included candidate before reporting this count.')+' Sato networks are never biological cell counts.'));csv.disabled=data.matched===0;summary.disabled=false;mask.disabled=false;refresh.hidden=true}catch(e){info.textContent=e.message;refresh.hidden=false}}
 prepare();
}
