'use strict';
// Review decisions are separate from annotation geometry and immutable label arrays.
const measurementState={serial:0,offset:0,filters:{status:'all',boundary:'all',sort:'id',search:''},host:null,data:null};
const decisionNames={unreviewed:'Unreviewed',accepted:'Accepted',rejected:'Rejected',needs_review:'Needs review'};
function measurementContext(){return {dataset:state.dataset,channel:state.channel,run:state.run}}
function measurementEligible(){const r=runMeta();return r&&!r.historical&&r.scope==='volume'&&r.method!=='preprocess'}
function measurementQuery(){return {...measurementContext(),...measurementState.filters,offset:measurementState.offset,limit:50}}
function measurementSame(q){return state.tab==='Review'&&q.dataset===state.dataset&&q.channel===state.channel&&q.run===state.run}
function measurementBadge(status){const b=expNode('span','decision-badge '+status,decisionNames[status]);return b}

const measurementReviewLayout=renderReviewWorkspace;
renderReviewWorkspace=function(){measurementReviewLayout();measurementState.serial++;measurementState.offset=0;measurementState.data=null;if(!measurementEligible())return;
 const host=expNode('section','measurement-panel');host.setAttribute('aria-label','Candidate measurements');measurementState.host=host;
 const header=expNode('div','measurement-heading');header.append(expNode('h2','','Candidate review & measurements'));const filterButton=expButton('⚑ Filters','measurement-filter-button',()=>{const d=expModal('Filter candidates','Choose which algorithm candidates appear in the review queue.','measurement-filter-dialog');controls.hidden=false;d.append(controls);const actions=expNode('div','dialog-actions');actions.append(expButton('Done','primary',()=>d.close()));d.append(actions);d.addEventListener('close',()=>{controls.hidden=true;if(host.isConnected)host.querySelector('.measurement-heading').after(controls)})});filterButton.title='Filter by decision, boundary contact, size order, or candidate ID';header.append(filterButton,expButton('Export selection ↗','exp-secondary',openMeasurementExport));host.append(header);
 const controls=expNode('div','measurement-filters');controls.hidden=true;
 for(const [key,label,choices] of [['status','Review status',[['all','All decisions'],...Object.entries(decisionNames)]],['boundary','Boundary policy',[['all','Include all edges'],['interior','Exclude edge contacts'],['edge','Edge contacts only']]],['sort','Sort candidates',[['id','Candidate ID'],['size_desc','Largest first'],['size_asc','Smallest first']]]]){
  const l=expNode('label','',label),select=document.createElement('select');select.setAttribute('aria-label',label);choices.forEach(([v,t])=>select.add(new Option(t,v)));select.value=measurementState.filters[key];select.onchange=()=>{measurementState.filters[key]=select.value;measurementState.offset=0;filterButton.classList.toggle('active',Object.values(measurementState.filters).some(v=>!['all','id',''].includes(v)));loadMeasurements()};l.append(select);controls.append(l);
 }
 const l=expNode('label','','Candidate ID'),search=document.createElement('input');search.type='search';search.placeholder='Exact ID';search.setAttribute('aria-label','Find candidate ID');search.value=measurementState.filters.search;let timer;search.oninput=()=>{measurementState.serial++;clearTimeout(timer);measurementState.filters.search=search.value;measurementState.offset=0;filterButton.classList.toggle('active',Object.values(measurementState.filters).some(v=>!['all','id',''].includes(v)));timer=setTimeout(loadMeasurements,200)};l.append(search);controls.append(l);host.append(controls);filterButton.classList.toggle('active',Object.values(measurementState.filters).some(v=>!['all','id',''].includes(v)));
 const summary=expNode('p','measurement-summary','Loading candidates…');summary.role='status';host.append(summary);host.append(expNode('div','measurement-table-wrap'));host.append(expNode('div','measurement-pagination'));$('#main-host').append(host);const jump=expButton('Candidates ↓','measurement-jump',()=>host.scrollIntoView({block:'start'}));$('#main-host .review-controls').append(jump);loadMeasurements();
};

async function loadMeasurements(){
 const host=measurementState.host;if(!host?.isConnected||!measurementEligible()||state.tab!=='Review')return;
 const q=measurementQuery(),serial=++measurementState.serial;host.classList.add('pending');
 try{const data=await api('/api/measurements?'+query(q));if(serial!==measurementState.serial||!host.isConnected||!measurementSame(q))return;measurementState.data=data;measurementState.offset=data.offset;
  host.querySelector('.measurement-summary').textContent=data.matched.toLocaleString()+' / '+data.total.toLocaleString()+' candidates · '+data.counts.accepted+' accepted · '+data.counts.needs_review+' need review · '+data.counts.rejected+' rejected. Selection: median '+(data.summary.median_voxels??'—')+' grid voxels; '+data.summary.edge_count+' touch a volume edge.';
  const wrap=host.querySelector('.measurement-table-wrap');wrap.replaceChildren();const table=expNode('table','measurement-table');table.setAttribute('aria-label','Candidate measurements table');const head=expNode('thead'),tr=expNode('tr');['Candidate','Decision','Grid voxels','Volume (µm³)','Volume edges'].forEach(t=>tr.append(expNode('th','',t)));head.append(tr);table.append(head);const body=expNode('tbody');
  for(const o of data.rows){const row=expNode('tr');row.dataset.object=o.id;const id=expNode('td');id.append(expButton('#'+o.id,'candidate-locate',()=>locateMeasurement(o.id)));row.append(id);const status=expNode('td');status.append(measurementBadge(o.status));row.append(status,expNode('td','',o.voxels.toLocaleString()),expNode('td','',o.volume_um3===null?'Uncalibrated':o.volume_um3.toLocaleString(undefined,{maximumFractionDigits:2})),expNode('td','',o.boundary_faces.join(', ')||'None'));body.append(row)}table.append(body);wrap.append(table);if(!data.rows.length)wrap.append(expNode('p','measurement-empty','No candidates match. Change the decision, edge or ID filter.'));
  const pagination=host.querySelector('.measurement-pagination');pagination.replaceChildren();const prev=expButton('← Previous','',()=>{measurementState.offset=Math.max(0,measurementState.offset-50);loadMeasurements()}),next=expButton('Next →','',()=>{measurementState.offset+=50;loadMeasurements()});prev.disabled=!data.offset;next.disabled=data.offset+data.rows.length>=data.matched;pagination.append(prev,expNode('span','',data.matched?`${data.offset+1}–${data.offset+data.rows.length} of ${data.matched}`:'0 candidates'),next);highlightMeasurement();
 }catch(e){if(serial===measurementState.serial&&host.isConnected){measurementState.data=null;host.querySelector('.measurement-summary').textContent=e.message;host.querySelector('.measurement-table-wrap').replaceChildren();host.querySelector('.measurement-pagination').replaceChildren()}}
 finally{if(serial===measurementState.serial)host.classList.remove('pending')}
}
let measurementLocateSerial=0;
async function locateMeasurement(id){const q={...measurementContext(),object:id},serial=++measurementLocateSerial;try{const data=await api('/api/object-location?'+query(q));if(serial!==measurementLocateSerial||!measurementSame(q))return;[reviewState.x,reviewState.y,state.z]=data.cursor;clampReviewCursor();scheduleReview();$('#desk').scrollTop=0;$('#task-panel').scrollTop=0;}catch(e){expNotice(e.message,'warning')}}
function highlightMeasurement(){const id=reviewState.data?.object?.id;measurementState.host?.querySelectorAll('tr[data-object]').forEach(row=>{row.classList.toggle('selected',Number(row.dataset.object)===id);row.querySelector('button').setAttribute('aria-pressed',String(Number(row.dataset.object)===id))})}
const measurementInspector=showObjectInspector;
showObjectInspector=function(data){measurementInspector(data);highlightMeasurement();if(!data.object||!measurementEligible())return;const box=$('#object-inspector');box.querySelector('h3').after(expButton('Review candidate #'+data.object.id,'review-decision-button',()=>openCandidateDecision(data.object)));if(data.object.note)box.append(expNode('p','candidate-note',data.object.note));};

function openCandidateDecision(obj){
 const q=measurementContext(),d=expModal('Review candidate #'+obj.id,'This decision records your assessment. It does not change the label volume or certify biological identity.','decision-dialog');
 const body=expNode('div','decision-form'),l=expNode('label','exp-field','Decision'),select=document.createElement('select');select.setAttribute('aria-label','Candidate decision');Object.entries(decisionNames).forEach(([v,t])=>select.add(new Option(t,v)));select.value=obj.status;l.append(select);body.append(l);
 const nl=expNode('label','exp-field','Review note'),note=document.createElement('textarea');note.maxLength=2000;note.rows=4;note.value=obj.note||'';note.setAttribute('aria-label','Candidate review note');nl.append(note);body.append(nl,expNode('p','',obj.boundary_faces.length?'Edge flags: '+obj.boundary_faces.join(', '):'No processed-volume edge contact.'));d.append(body);
 const message=expNode('p','decision-message');message.role='status';d.append(message);const actions=expNode('footer','decision-actions');const save=expButton('Save decision','exp-run',async()=>{if(!measurementSame(q)){message.textContent='The active run changed. Close and reopen this review.';return}save.disabled=true;message.textContent='Saving decision…';try{await api('/api/object-decision',{...q,object:obj.id,status:select.value,note:note.value,expected_revision:obj.review_revision});d.close();if(measurementSame(q)){loadMeasurements();reviewState.signature=null;scheduleReview()}expNotice('Candidate #'+obj.id+' · '+decisionNames[select.value]+' saved.')}catch(e){message.textContent=e.message;save.disabled=false;reload.hidden=false}});
 const reload=expButton('Reload latest decision','',async()=>{reload.disabled=true;try{const latest=await api('/api/measurements?'+query({...q,search:obj.id}));if(!d.isConnected)return;const row=latest.rows[0];obj={...obj,...row,review_revision:latest.revision};select.value=obj.status;note.value=obj.note;message.textContent='Latest decision loaded. Confirm your changes before saving.';reload.hidden=true}catch(e){message.textContent=e.message}finally{reload.disabled=false}});reload.hidden=true;actions.append(reload,expButton('Cancel','',()=>d.close()),save);d.append(actions);
}

async function openMeasurementExport(){
 const q={...measurementContext(),...measurementState.filters},d=expModal('Export candidate measurements','Exports the entire filtered selection across all pages. Decisions and boundary policy are explicit; segmentation stays unchanged.','measurement-export');
 const info=expNode('div','export-preview');info.role='status';info.textContent='Preparing export preview…';d.append(info);const actions=expNode('footer','decision-actions'),download=expButton('Download CSV','exp-run',async()=>{download.disabled=true;try{const response=await fetch('/api/measurements.csv?'+query(q));if(!response.ok){const err=await response.json();throw Error(err.error)}const blob=await response.blob(),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='candidates-'+q.run.slice(0,8)+'-'+q.status+'.csv';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);d.close();expNotice('Measurement CSV downloaded.')}catch(e){info.textContent=e.message;download.disabled=true;refresh.hidden=false}});download.disabled=true;
 const refresh=expButton('Refresh export preview','',prepare);refresh.hidden=true;actions.append(refresh,expButton('Cancel','',()=>d.close()),download);d.append(actions);
 async function prepare(){download.disabled=true;try{const data=await api('/api/measurements?'+query({...q,limit:5}));if(!d.isConnected)return;q.revision=data.revision||'';info.replaceChildren(expNode('h3','',data.matched+(data.matched===1?' candidate will':' candidates will')+' be exported'),expNode('p','','Decision filter: '+(decisionNames[q.status]||'All decisions')+' · Edge policy: '+q.boundary),expNode('p','','Source dataset: '+q.dataset+' · Channel '+(q.channel+1)+' · Run '+q.run),expNode('p','','Review revision: '+(data.revision||'No decisions yet')),expNode('p','','Includes grid voxel count, calibrated volume when available, native bounds, edge flags, source hash, run ID and notes. '+data.meaning));if(q.status!=='accepted')info.append(expNode('p','export-warning','This selection includes decisions other than Accepted. Choose Accepted in the table filter to export only accepted candidates.'));download.disabled=data.matched===0;refresh.hidden=true;}catch(e){info.textContent=e.message;refresh.hidden=false}}
 prepare();
}
