'use strict';
// Canvas tools operate in native image coordinates. Display gestures never resample stored annotations.
state.traceGesture='click';state.selected=null;state.annotationLabel='';state.redo=[];state.compareGrid=false;
if(!state.author){state.author='Guest '+crypto.randomUUID().slice(0,4);localStorage.setItem('studio-author',state.author)}
let saving=false,saveTimer=null,recipeList=[],spaceHeld=false;
const saveState=message=>$('#save-state').textContent=message;
function queueDraft(){clearTimeout(saveTimer);saveState('Unsaved changes');saveTimer=setTimeout(async()=>{
 try{localStorage.setItem('field-draft:'+state.dataset,JSON.stringify({base:state.revision,items:state.items}));}catch(e){status('Browser draft storage full; save or export your work',true)}
 if(!state.dirty||saving||state.pending.length)return;
 saving=true;saveState('Saving…');try{await saveAnnotations();if(!state.dirty)localStorage.removeItem('field-draft:'+state.dataset);saveState(state.dirty?'Changes waiting':'Saved ✓')}catch(e){saveState('Save failed · retry');status(e.message,true)}finally{saving=false;if(state.dirty&&!$('#save-state').textContent.startsWith('Save failed'))queueDraft()}
 },1100)}
const baseSnapshot=snapshot;snapshot=function(){state.redo=[];baseSnapshot();queueDraft()};
const baseLoadAnnotations=loadAnnotations;loadAnnotations=async function(){await baseLoadAnnotations();state.redo=[];state.selected=null;saveState('Saved ✓');try{const draft=JSON.parse(localStorage.getItem('field-draft:'+state.dataset)||'null');if(draft&&draft.base===state.revision){state.items=draft.items;state.dirty=true;queueDraft();status('Recovered your browser draft')}}catch(e){status('Could not recover browser draft',true)}};
function undoStudio(redo=false){if(state.pending.length){if(!redo){state.pending.pop();scheduleDraw()}return}const from=redo?state.redo:state.undo,to=redo?state.undo:state.redo;if(!from.length)return;to.push(structuredClone(state.items));state.items=from.pop();state.dirty=true;state.selected=null;updateAnnotationPanels();scheduleDraw();queueDraft()}
function removeSelected(){if(!state.selected)return;snapshot();state.items=state.items.filter(it=>it.id!==state.selected);state.selected=null;updateAnnotationPanels();scheduleDraw();queueDraft()}
function setTool(tool){if(tool!==state.tool&&state.pending.length){status('Finish or discard the drawing before choosing another tool',true);return}if(tool!==state.tool)cancelDraft();state.tool=tool;document.querySelectorAll('[data-tool]').forEach(e=>e.value=tool);document.querySelectorAll('[data-canvas-tool]').forEach(e=>{e.classList.toggle('active',e.dataset.canvasTool===tool);e.setAttribute('aria-pressed',String(e.dataset.canvasTool===tool))});document.querySelectorAll('.viewport canvas').forEach(c=>c.style.cursor=tool==='navigate'?'grab':tool==='select'?'default':'crosshair');syncTraceUI();scheduleDraw()}
const baseFinish=finishDrawing;finishDrawing=function(){const free=state.tool==='freehand';if(free)state.tool='polygon';baseFinish();if(free)state.tool='freehand';queueDraft()};
const baseDrawAnnotation=drawAnnotation;drawAnnotation=function(ctx,it,s){baseDrawAnnotation(ctx,it,s);if(it.id!==state.selected)return;ctx.fillStyle='#ffc778';for(const [x,y] of it.points){ctx.beginPath();ctx.arc(x,y,3/s,0,Math.PI*2);ctx.fill()}};
function nativePoint(v,e){const t=v.transform,rect=v.querySelector('canvas').getBoundingClientRect();if(!t)return null;const x=(e.clientX-rect.left-t.ox)/t.s,y=(e.clientY-rect.top-t.oy)/t.s;if(x<0||y<0||x>state.meta.shape[3]-1||y>state.meta.shape[2]-1)return null;return [x,y]}
function visibleItems(v){return state.items.filter(it=>it.channel===state.channel&&(v.dataset.kind==='volume'?it.domain==='volume'||it.domain==='slice':it.domain===v.dataset.kind&&(it.domain!=='slice'||it.z===state.z)))}
function selectHit(v,e){const c=v.querySelector('canvas'),rect=c.getBoundingClientRect(),pos=[e.clientX-rect.left,e.clientY-rect.top];let best=null,dist=12;for(const it of visibleItems(v)){it.points.forEach((p,i)=>{const q=v.dataset.kind==='volume'?v.project?.(p[0],p[1],it.domain==='volume'?p[2]:it.z):[v.transform.ox+p[0]*v.transform.s,v.transform.oy+p[1]*v.transform.s];if(!q)return;const d=Math.hypot(q[0]-pos[0],q[1]-pos[1]);if(d<dist){best={it,index:i};dist=d}})}return best}
function volumePoint(v,e){if(!v.project||!v.samplePoints)return null;const rect=v.querySelector('canvas').getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;let best=null,distance=10;for(const p of v.samplePoints){const q=v.project(p[0],p[1],p[2]),d=Math.hypot(q[0]-x,q[1]-y);if(d<distance){distance=d;best=p.slice(0,3)}}return best}
const baseBindCanvas=bindCanvas;bindCanvas=function(v){baseBindCanvas(v);const c=v.querySelector('canvas'),down=c.onpointerdown,move=c.onpointermove,up=c.onpointerup,cancel=c.onpointercancel;let gesture=null;
 c.onpointerdown=e=>{c.focus({preventScroll:true});if(e.button!==0||spaceHeld||state.tool==='navigate'){gesture={pan:true};down(e);return}if(state.tool==='select'){const hit=selectHit(v,e);state.selected=hit?.it.id||null;gesture=hit&&v.dataset.kind!=='volume'?{edit:hit,start:nativePoint(v,e),original:structuredClone(hit.it.points),changed:false}:null;c.setPointerCapture(e.pointerId);scheduleDraw();updateAnnotationPanels();return}
 if(v.dataset.kind==='volume'){gesture={volume:true,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId);return}
 if(state.tool==='freehand'||(state.tool==='polyline'&&state.traceGesture==='freehand')){const p=nativePoint(v,e);if(!p)return;state.pending=[p];state.pendingDomain=v.dataset.kind;gesture={freehand:true};c.setPointerCapture(e.pointerId);scheduleDraw();return}down(e)};
 c.onpointermove=e=>{if(gesture?.edit){const p=nativePoint(v,e);if(!p||!gesture.start)return;if(!gesture.changed){snapshot();gesture.changed=true}gesture.edit.it.points[gesture.edit.index]=p;scheduleDraw();return}if(gesture?.freehand){const p=nativePoint(v,e),last=state.pending.at(-1);if(p&&Math.hypot(p[0]-last[0],p[1]-last[1])*v.transform.s>2){state.pending.push(p);scheduleDraw()}return}if(gesture?.volume)return;if(gesture?.pan&&state.tool!=='navigate'){const old=state.tool;state.tool='navigate';move(e);state.tool=old}else move(e)};
 c.onpointerup=e=>{if(gesture?.edit){if(gesture.changed){queueDraft();updateAnnotationPanels()}gesture=null;return}if(gesture?.freehand){gesture=null;finishDrawing();return}if(gesture?.volume){const g=gesture;gesture=null;if(Math.hypot(e.clientX-g.x,e.clientY-g.y)>4)return;if(state.tool==='polygon'||state.tool==='freehand'){status('Outline cells on the slice pane; 3D supports landmarks and traces');return}const p=volumePoint(v,e);if(!p){status('Click a visible signal point to place a 3D landmark');return}if(state.pending.length&&state.pendingDomain!=='volume'){status('Finish the current drawing first');return}state.pendingDomain='volume';state.pending.push(p);if(state.tool==='point')finishDrawing();else scheduleDraw();status('3D point anchored at X '+Math.round(p[0])+', Y '+Math.round(p[1])+', Z '+(p[2]+1)+' • check depth before accepting');return}if(gesture?.pan&&state.tool!=='navigate'){const old=state.tool;state.tool='navigate';up(e);state.tool=old}else up(e);gesture=null};
 c.onpointercancel=()=>{if(gesture?.edit?.it&&gesture.changed)gesture.edit.it.points=gesture.original;if(gesture?.freehand)cancelDraft();gesture=null;cancel?.();scheduleDraw()};
};
function toolPalette(){const el=document.createElement('div');el.className='floating-tools';el.setAttribute('aria-label','Annotation tools');const defs=[['navigate','↖','Pan','V'],['select','⌖','Select','S'],['point','⊙','Point','P'],['polygon','⬡','Outline','O'],['freehand','〰','Draw','B'],['polyline','⌁','Neurite','L']];for(const [tool,icon,label,key] of defs){const b=document.createElement('button');b.dataset.canvasTool=tool;b.innerHTML=toolIcon(tool)+'<span>'+label+'</span>';b.title=label+' ('+key+')';b.setAttribute('aria-label',label+' tool');b.classList.toggle('active',state.tool===tool);b.onclick=()=>setTool(tool);el.append(b)}const divider=document.createElement('span');divider.className='divider';el.append(divider);for(const [label,title,fn] of [['↶','Undo',()=>undoStudio()],['↷','Redo',()=>undoStudio(true)],['✓','Finish drawing',finishDrawing]]){const b=document.createElement('button');b.innerHTML=toolIcon({'Undo':'undo','Redo':'redo','Finish drawing':'finish'}[title]);b.title=title;b.setAttribute('aria-label',title);b.onclick=fn;el.append(b)}return el}
function decorateAnnotations(){
 const tool=$('#task-panel .tool');if(!tool)return;
 const list=tool.querySelector('[data-annotation-list]'),exports=tool.querySelector('[data-export]'),author=tool.querySelector('[data-author]').closest('label'),imported=tool.querySelector('[data-import]').closest('label'),save=tool.querySelector('[data-save]'),reload=tool.querySelector('[data-reload]');
 tool.classList.add('annotation-workbench');tool.replaceChildren();
 const top=document.createElement('div');top.className='annotation-head';top.innerHTML='<div class="annotation-title"><h2>Annotate</h2><div class="annotation-count"><strong>'+state.items.length+'</strong><span>marks</span></div></div><label>Label for new marks<input class="annotation-label" aria-label="Annotation label" placeholder="e.g. Neuron 1 · branch A"></label><div class="context-tools"></div>';
 const label=top.querySelector('input');label.value=state.annotationLabel;label.oninput=e=>state.annotationLabel=e.target.value;tool.append(top);
 const selection=document.createElement('div');selection.className='selection-editor';selection.hidden=true;selection.innerHTML='<label>Selected mark<input aria-label="Selected mark label"></label><div class="edit-actions"><button data-rename>Rename</button><button data-delete-selected>Delete selected</button></div>';selection.querySelector('[data-rename]').onclick=()=>{const it=state.items.find(x=>x.id===state.selected);if(!it)return;snapshot();it.label=selection.querySelector('input').value.trim();updateAnnotationPanels();scheduleDraw()};selection.querySelector('[data-delete-selected]').onclick=removeSelected;tool.append(selection);
 const filter=document.createElement('input');filter.className='mark-search';filter.type='search';filter.placeholder='Find a label…';filter.setAttribute('aria-label','Find annotations');filter.value=state.markSearch||'';filter.oninput=e=>{state.markSearch=e.target.value;filterMarks()};tool.append(filter);
 const scroll=document.createElement('div');scroll.className='mark-scroll';scroll.append(list);tool.append(scroll);
 const bottom=document.createElement('div');bottom.className='annotation-bottom';const bar=document.createElement('div');bar.className='save-bar';save.classList.add('primary');save.textContent='Save now';save.onclick=safe(async()=>{await saveAnnotations();saveState('Saved ✓');syncWorkbench()});reload.textContent='Reload';bar.append(save,reload);bottom.append(bar);const details=document.createElement('details');details.className='annotation-files';details.innerHTML='<summary>Export, import & annotator</summary>';details.append(exports,author,imported);bottom.append(details);const note=document.createElement('p');note.className='storage-note';note.textContent='Autosaved in this browser · back up important work';bottom.append(note);tool.append(bottom);syncWorkbench();
}
function filterMarks(){const q=(state.markSearch||'').toLowerCase();document.querySelectorAll('#task-panel .annotation-row').forEach(row=>row.hidden=!row.textContent.toLowerCase().includes(q))}
function syncWorkbench(){const editor=$('.selection-editor'),selected=state.items.find(it=>it.id===state.selected);if(editor){editor.hidden=!selected;if(selected&&editor.dataset.id!==selected.id){editor.querySelector('input').value=selected.label||'';editor.dataset.id=selected.id}if(!selected)delete editor.dataset.id}filterMarks();const pending=state.pending.length;document.querySelectorAll('[data-save]').forEach(b=>b.disabled=!!pending);const bar=$('.draft-actions');if(bar){bar.hidden=!pending;bar.querySelector('span').textContent=pending+' points · unfinished '+(state.tool==='polyline'?'trace':'outline');bar.querySelector('[data-finish-draft]').disabled=pending<(state.tool==='polygon'||state.tool==='freehand'?3:2)}if(pending)saveState('Drawing · not saved');else if($('#save-state').textContent==='Drawing · not saved')saveState(state.dirty?'Unsaved changes':'Saved ✓');document.querySelectorAll('.floating-tools button').forEach(b=>{const name=b.getAttribute('aria-label');if(b.dataset.canvasTool){b.setAttribute('aria-pressed',String(b.dataset.canvasTool===state.tool));b.disabled=state.annotationView==='volume'&&['polygon','freehand'].includes(b.dataset.canvasTool)}if(name==='Undo')b.disabled=!pending&&!state.undo.length;if(name==='Redo')b.disabled=!!pending||!state.redo.length;if(name==='Finish drawing')b.disabled=!pending||pending<(state.tool==='polygon'?3:2)})}

const baseUpdatePanels=updateAnnotationPanels;updateAnnotationPanels=function(){baseUpdatePanels();const count=$('.annotation-count strong');if(count)count.textContent=state.items.length;const del=$('.edit-actions button');if(del)del.disabled=!state.selected;syncWorkbench()};
const baseFillList=fillAnnotationList;fillAnnotationList=function(el){baseFillList(el);[...el.children].forEach((row,i)=>{const it=state.items[i];if(it.label)row.querySelector('span').textContent=it.label+' · '+it.type+' · '+(it.domain==='volume'?'3D':it.domain);if(it.type==='polyline'){const title=row.querySelector('span');title.textContent=(it.label||'Neurite trace')+' · '+traceMeasurement(it.points,it.domain);}row.querySelectorAll('button').forEach(b=>{if(b.textContent==='Show')b.onclick=()=>{if(state.pending.length){status('Finish or discard the drawing before selecting another mark',true);return}if(state.annotationView!=='both')state.annotationView=it.domain==='volume'?'volume':'slice';state.selected=it.id;state.channel=it.channel;state.mode=it.domain==='volume'?'volume':it.domain;state.z=it.z;state.tool='select';$('#channel').value=state.channel;$('#z').value=it.z;renderLayout()}})})};
function recipeParameters(tool){const p={};tool.querySelectorAll('[name]').forEach(n=>p[n.name]=n.type==='checkbox'?n.checked:n.value);delete p.parent;return p}
function applyRecipe(params){state.recipe={...params,parent:''};renderLayout();status('Recipe applied • confirm the channel and preview scope before running')}
function decorateProcess(){const tool=$('#task-panel .tool');if(!tool)return;tool.querySelector('h2').textContent='Build a processing recipe';const rn=document.createElement('input');rn.type='hidden';rn.name='recipe_name';rn.value=state.recipe.recipe_name||'';tool.append(rn);const library=document.createElement('div');library.className='recipe-library';library.innerHTML='<h3>Start with a recipe</h3><p class="muted">Choose a starting point, then map it to your image channel.</p>';const select=document.createElement('select');select.setAttribute('aria-label','Recipe library');select.add(new Option('Choose a recipe…',''));const presets=[{name:'Nuclei · watershed candidates',parameters:{method:'watershed',scope:'volume',factor:2,sigma:1,background:0,min_size:30,distance:5,threshold:1}},{name:'Cell bodies · connected regions',parameters:{method:'otsu',scope:'volume',factor:2,sigma:.6,background:0,min_size:30,threshold:1}},{name:'Neurites · ridge network',parameters:{method:'sato',scope:'volume',factor:2,sigma:0,background:0,min_size:15,threshold:1}}];presets.forEach(p=>p.parameters.factor=Number(state.recipe.factor)||2);const all=[...presets,...recipeList];all.forEach((r,i)=>select.add(new Option(r.name,String(i))));select.onchange=()=>{if(select.value!=='')applyRecipe({...all[+select.value].parameters,recipe_name:all[+select.value].name})};library.append(select);tool.querySelector('h2').after(library);const save=document.createElement('div');save.className='recipe-save';save.innerHTML='<label>Save a reusable recipe<input placeholder="e.g. Myo7a · baseline" aria-label="Recipe name"></label><button class="primary">Save recipe</button>';save.querySelector('button').onclick=safe(async()=>{const name=save.querySelector('input').value;const recipe=await api('/api/recipes',{name,parameters:recipeParameters(tool)});recipeList.push(recipe);renderLayout();status('Recipe saved: '+recipe.name)});tool.append(save);tool.querySelector('[data-run]').classList.add('primary');}
const baseCatalog=resultCatalog;resultCatalog=function(){baseCatalog();const search=$('#result-search')?.value.toLowerCase()||'';document.querySelectorAll('.result-button[data-result]').forEach(b=>{const r=state.runs.find(r=>r.id===b.dataset.result);const badge=document.createElement('span');badge.className='run-badge';badge.textContent=r.historical?'◷ Saved output · view only':'● Local method · rerunnable';b.append(badge);b.hidden=!b.textContent.toLowerCase().includes(search)})};$('#result-search').oninput=resultCatalog;
const baseLayout=renderLayout;renderLayout=function(){if(state.tab!=='Annotate')state.tool='navigate';baseLayout();if(!state.meta)return;document.body.classList.toggle('student',state.tab==='Annotate');document.querySelector('.mode-buttons').hidden=state.tab==='Annotate';$('#compare-grid').hidden=state.tab==='Annotate';const host=$('#main-host');host.classList.remove('annotation-layout','compare-four');if(state.tab==='Annotate'){host.replaceChildren(newViewport('slice',false,'annotation-slice'),newViewport('volume',false,'annotation-volume'));host.classList.add('annotation-layout');$('#desk').append(toolPalette());const hint=document.createElement('div');hint.className='canvas-hint';hint.textContent='Space + drag to move · P point · B draw · Enter finish · ⌘ Z undo';$('#desk').append(hint);decorateAnnotations();addTraceControls();addAnnotationWorkspace()}else{$('#desk .floating-tools')?.remove();$('#desk .canvas-hint')?.remove();if(state.compareGrid){host.replaceChildren();host.classList.add('compare-four');const ids=['',state.run,...state.runs.filter(r=>r.id!==state.run&&canShow(r,state.mode)).map(r=>r.id)].filter((v,i,a)=>a.indexOf(v)===i).slice(0,4);ids.forEach((id,i)=>{const v=newViewport(state.mode,!id,'grid-'+i);v.overrideRun=id;host.append(v)})}if(state.tab==='Process')decorateProcess()}
 // Remove tools from the previous render without disturbing the image canvases.
 document.querySelectorAll('.floating-tools').forEach((e,i,a)=>{if(i<a.length-1)e.remove()});document.querySelectorAll('.canvas-hint').forEach((e,i,a)=>{if(i<a.length-1)e.remove()});
 host.querySelectorAll('.viewport').forEach((v,i)=>{const name=document.createElement('div');name.className='pane-name';name.textContent=state.tab==='Annotate'?(i?'3D context':'Draw on this slice'):(v.raw?'Reference':'Result');v.append(name)});scheduleDraw();};
const gridButton=document.createElement('button');gridButton.id='compare-grid';gridButton.textContent='⊞ Compare grid';gridButton.onclick=()=>{state.compareGrid=!state.compareGrid;gridButton.classList.toggle('active',state.compareGrid);renderLayout()};$('#more-tools').before(gridButton);
const preview=document.createElement('div');preview.id='import-preview';$('#import-name').after(preview);$('#source-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#import-name').textContent=file.name;$('#import-dialog').showModal();preview.textContent='Reading dimensions…';try{const r=await fetch('/api/inspect-source?'+query({name:file.name}),{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Studio-Request':'1'},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);preview.textContent=d.axes.split('').map((a,i)=>a+' '+d.shape[i]).join(' × ')+' · '+d.dtype+' · '+(file.size/1048576).toFixed(1)+' MB';if(d.series>1)preview.textContent+=' · '+d.series+' series (imports first series only)';}catch(e){preview.textContent=e.message}};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||e.target.isContentEditable)return;if(e.code==='Space'){e.preventDefault();spaceHeld=true}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoStudio(e.shiftKey);return}if(e.key==='Escape'){setTool('navigate');return}if(e.key==='Enter'&&state.pending.length){e.preventDefault();finishDrawing()}if((e.key==='Delete'||e.key==='Backspace')&&state.selected){e.preventDefault();removeSelected()}if(state.tab==='Annotate'&&!e.metaKey&&!e.ctrlKey){const t={v:'navigate',s:'select',p:'point',o:'polygon',b:'freehand',l:'polyline'}[e.key.toLowerCase()];if(t)setTool(t)}});document.addEventListener('keyup',e=>{if(e.code==='Space')spaceHeld=false});window.addEventListener('blur',()=>spaceHeld=false);
Promise.all([api('/api/recipes'),api('/api/config')]).then(([recipes,config])=>{recipeList=recipes;state.processLimit=config.process_limit;if(config.shared){const banner=document.createElement('div');banner.className='shared-banner';banner.textContent='Shared public demo · synthetic starter scans · uploads and saved annotations are visible to other visitors · '+config.upload_limit_mb+' MB upload limit';document.querySelector('nav').before(banner)}if(state.meta)renderLayout()}).catch(e=>status(e.message,true));

// Small shared icon and control vocabulary; inline SVG stays available offline.
function toolIcon(name){const paths={undo:'M9 5 4 10l5 5M4 10h10a6 6 0 0 1 6 6',redo:'m15 5 5 5-5 5M20 10H10a6 6 0 0 0-6 6',finish:'m5 12 4 4L19 6',navigate:'M5 3v15l4-4 4 7 3-2-4-7h6Z',select:'M8 3H3v5M16 3h5v5M21 16v5h-5M8 21H3v-5',point:'M12 8v8M8 12h8M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',polygon:'m4 7 8-4 8 7-3 10H6Z',freehand:'M3 18C2 8 11 2 12 8S7 21 16 16s6-9 5-11',polyline:'m3 19 5-8 5 3 8-11M8 11l-3-7'};return '<svg class="ui-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+paths[name]+'"/></svg>'}
function traceMeasurement(points,domain){const calibrated=state.meta?.calibrated!==false,spacing=calibrated?(state.meta?.spacing||[1,1,1]):[1,1,1];let length=0;for(let i=1;i<points.length;i++){const a=points[i-1],b=points[i];length+=Math.hypot((b[0]-a[0])*spacing[0],(b[1]-a[1])*spacing[1],domain==='volume'?(b[2]-a[2])*spacing[2]:0)}return length.toFixed(1)+' '+(calibrated?'µm':domain==='volume'?'voxels':'px')+' · '+(domain==='volume'?'3D':domain==='projection'?'2D projected':'2D slice')}
function syncTraceUI(){const panel=$('#trace-controls');if(!panel)return;const tracing=state.tool==='polyline';panel.hidden=!tracing;panel.querySelectorAll('[data-trace-gesture]').forEach(b=>{const active=tracing&&state.traceGesture===b.dataset.traceGesture;b.disabled=!!state.pending.length;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});const pending=tracing&&state.pending.length;panel.querySelector('[data-trace-length]').textContent=pending?state.pending.length+' points · '+traceMeasurement(state.pending,state.pendingDomain):tracing?'Ready to trace':'Choose a tracing mode to start';panel.querySelector('[data-trace-finish]').disabled=!pending||state.pending.length<2;panel.querySelector('[data-trace-back]').disabled=!pending;panel.querySelector('[data-trace-help]').textContent=tracing?(state.traceGesture==='freehand'?'Drag along a neurite on the slice; release to save an open line.':'Click along a neurite, then Finish trace or Enter. In 3D, clicks anchor to visible sampled voxels.'): 'Open lines measure neurite length. Outlines measure closed cell boundaries.';const hint=$('#desk .canvas-hint');if(hint)hint.textContent=tracing?'L neurite · Enter finish · Backspace last point · Space + drag to pan':'Space + drag to move · P point · L neurite · B outline · ⌘ Z undo'}
function addTraceControls(){const box=document.createElement('section');box.id='trace-controls';box.className='trace-card';box.innerHTML='<h3>Neurite tracing <kbd>L</kbd></h3><div class="segmented" role="group" aria-label="Neurite tracing mode"><button data-trace-gesture="click">Click points</button><button data-trace-gesture="freehand">Freehand line</button></div><output data-trace-length aria-live="off" aria-label="Trace length"></output><p data-trace-help></p><div class="trace-actions"><button data-trace-back>Remove last point</button><button data-trace-finish class="primary">Finish trace</button></div>';box.querySelectorAll('[data-trace-gesture]').forEach(b=>b.onclick=()=>{state.traceGesture=b.dataset.traceGesture;setTool('polyline')});box.querySelector('[data-trace-finish]').onclick=finishDrawing;box.querySelector('[data-trace-back]').onclick=()=>{state.pending.pop();scheduleDraw()};$('#task-panel .context-tools').append(box);syncTraceUI()}
const tracingDraw=scheduleDraw;scheduleDraw=function(){tracingDraw();syncTraceUI();syncWorkbench()};
const tracingAnnotation=drawAnnotation;drawAnnotation=function(ctx,it,s){tracingAnnotation(ctx,it,s);if(it.type!=='polyline'||!it.points.length)return;ctx.fillStyle=it.id===state.selected?'#ffc778':'#57ddff';for(const [x,y] of (it.status==='draft'&&state.traceGesture==='click'?it.points:[it.points[0],it.points.at(-1)])){ctx.beginPath();ctx.arc(x,y,3/s,0,Math.PI*2);ctx.fill()}};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||e.target.isContentEditable)return;if(e.key==='Backspace'&&state.tool==='polyline'&&state.pending.length){e.preventDefault();e.stopImmediatePropagation();state.pending.pop();scheduleDraw()}},true);

let processingRequest=false;
const processDesign=decorateProcess;decorateProcess=function(){processDesign();const tool=$('#task-panel .tool');if(!tool)return;const method=tool.querySelector('[name=method]'),scope=tool.querySelector('[name=scope]'),factor=tool.querySelector('[name=factor]');const help=document.createElement('p');help.className='method-help';method.closest('label').after(help);const ridge=document.createElement('label');ridge.textContent='Sato dimensions';const dimensions=document.createElement('select');dimensions.name='sato_mode';dimensions.add(new Option('2D filter per Z slice','slice'));dimensions.add(new Option('3D grid filter (equal-axis assumption)','volume'));dimensions.value=state.recipe.sato_mode||'slice';dimensions.onchange=()=>state.recipe.sato_mode=dimensions.value;ridge.append(dimensions);help.after(ridge);const size=document.createElement('p');size.className='processing-size';size.setAttribute('role','status');tool.querySelector('[data-run]').before(size);
 const describe=()=>{const texts={otsu:'Separates bright foreground from background, then labels connected regions. Touching cells may remain joined.',watershed:'Uses a foreground mask and distance peaks to split touching regions into candidate objects. Seed spacing controls splitting.',sato:'Enhances bright ridges and labels connected networks. Components are not individual neurons. Ridge scales use grid pixels; anisotropic Z spacing can affect 3D responses.',preprocess:'Saves a filtered intensity image without segmentation. Use it as input for a later volume run.'};help.textContent=texts[method.value];ridge.hidden=method.value!=='sato';if(method.value==='sato'){const spacing=state.meta.spacing||[1,1,1];help.textContent+=' Z / working XY spacing: '+(spacing[2]/(spacing[0]*Number(factor.value))).toFixed(2)+'. Per-slice mode filters in XY; connected components may still span Z.'}tool.querySelector('[name=distance]').closest('label').hidden=method.value!=='watershed';for(const name of ['threshold','min_size'])tool.querySelector('[name='+name+']').closest('label').hidden=method.value==='preprocess';const [z,c,y,x]=state.meta.shape,f=+factor.value,n=(scope.value==='volume'?z:1)*Math.floor(y/f)*Math.floor(x/f),limit=state.processLimit;const invalid=x%f||y%f,large=limit&&n>limit;size.textContent=invalid?'Choose a resolution that divides the image dimensions.':(n/1e6).toFixed(2)+' million processing pixels/voxels'+(large?' — exceeds '+(limit/1e6)+'M limit. Choose 4× XY or a slice/projection.':' · '+f+'× XY; source unchanged');size.classList.toggle('error',!!(large||invalid));tool.querySelectorAll('[data-run],[data-batch]').forEach(b=>b.disabled=!!(large||invalid||processingRequest));return !large&&!invalid};
 tool.addEventListener('change',describe);describe();for(const selector of ['[data-run]','[data-batch]']){const button=tool.querySelector(selector),handler=button.onclick;button.onclick=async e=>{if(processingRequest||!describe())return;processingRequest=true;const label=button.textContent;button.textContent='Processing…';describe();status('Processing on this device… results will appear in the left sidebar');try{await handler(e)}finally{processingRequest=false;button.textContent=label;if(tool.isConnected)describe();else if(state.tab==='Process')renderLayout()}}}
};
const resultDetails=resultCatalog;resultCatalog=function(){resultDetails();const current=runMeta(),box=$('.selected-actions');if(!current||current.historical||!box)return;const count=document.createElement('p');count.className='muted';count.textContent=current.method==='preprocess'?'Preprocessed intensity image; no segmentation.':current.objects+' '+(current.method==='sato'?'connected networks':'candidate regions')+' · '+current.seconds+' s';box.prepend(count);if(current.ridge_response){const a=link('runs/'+current.id+'/ridge-response.tif','Download ridge response');box.append(a)}box.append(link('runs/'+current.id+'/run.json','Recipe & provenance'))};

state.annotationView='both';
function addAnnotationWorkspace(){
 const host=$('#main-host');host.classList.toggle('annotation-solo',state.annotationView!=='both');for(const v of host.querySelectorAll('.viewport'))v.hidden=state.annotationView!=='both'&&v.dataset.kind!==state.annotationView;
 const controls=document.createElement('div');controls.className='annotation-view-choice';controls.setAttribute('aria-label','Annotation workspace layout');for(const [value,label] of [['both','2D + 3D'],['slice','2D only'],['volume','3D only']]){const b=document.createElement('button');b.textContent=label;b.classList.toggle('active',value===state.annotationView);b.setAttribute('aria-pressed',String(value===state.annotationView));b.onclick=()=>{if(state.pending.length){status('Finish or discard the drawing before changing views',true);return}state.annotationView=value;if(value==='volume'&&['polygon','freehand'].includes(state.tool))state.tool='navigate';renderLayout()};controls.append(b)}$('#desk').append(controls);
 const draft=document.createElement('div');draft.className='draft-actions';draft.innerHTML='<span></span><button data-discard-draft>Discard</button><button data-finish-draft class="primary">Finish · Enter</button>';draft.querySelector('[data-discard-draft]').onclick=()=>{cancelDraft();scheduleDraw()};draft.querySelector('[data-finish-draft]').onclick=finishDrawing;$('#desk').append(draft);
 for(const name of ['annotation-view-choice','draft-actions']){const all=document.querySelectorAll('.'+name);all.forEach((el,i)=>{if(i<all.length-1)el.remove()})}syncWorkbench();
}
const usabilityLayout=renderLayout;renderLayout=function(){usabilityLayout();if(state.tab!=='Annotate')document.querySelectorAll('.annotation-view-choice,.draft-actions').forEach(e=>e.remove())};
