'use strict';
// Canvas tools operate in native image coordinates. Display gestures never resample stored annotations.
state.selected=null;state.annotationLabel='';state.redo=[];state.compareGrid=false;
if(!state.author){state.author='Guest '+crypto.randomUUID().slice(0,4);localStorage.setItem('studio-author',state.author)}
let saving=false,saveTimer=null,recipeList=[],spaceHeld=false;
const saveState=message=>$('#save-state').textContent=message;
function queueDraft(){clearTimeout(saveTimer);saveState('Unsaved changes');saveTimer=setTimeout(async()=>{
 try{localStorage.setItem('field-draft:'+state.dataset,JSON.stringify({base:state.revision,items:state.items}));}catch(e){status('Browser draft storage full; save or export your work',true)}
 if(!state.dirty||saving||state.pending.length)return;
 saving=true;saveState('Saving…');try{await saveAnnotations();if(!state.dirty)localStorage.removeItem('field-draft:'+state.dataset);saveState(state.dirty?'Changes waiting':'Saved ✓')}catch(e){saveState('Save failed · retry');status(e.message,true)}finally{saving=false;if(state.dirty&&!$('#save-state').textContent.startsWith('Save failed'))queueDraft()}
 },1100)}
const baseSnapshot=snapshot;snapshot=function(){state.redo=[];baseSnapshot();queueDraft()};
const baseLoadAnnotations=loadAnnotations;loadAnnotations=async function(){await baseLoadAnnotations();state.redo=[];state.selected=null;saveState('Saved ✓');try{const draft=JSON.parse(localStorage.getItem('field-draft:'+state.dataset)||'null');if(draft&&draft.base===state.revision){state.items=draft.items;state.dirty=true;queueDraft();status('Recovered your browser draft')}}catch(e){status('Could not recover browser draft',true)}};
function undoStudio(redo=false){const from=redo?state.redo:state.undo,to=redo?state.undo:state.redo;if(!from.length)return;to.push(structuredClone(state.items));state.items=from.pop();state.dirty=true;state.selected=null;updateAnnotationPanels();scheduleDraw();queueDraft()}
function removeSelected(){if(!state.selected)return;snapshot();state.items=state.items.filter(it=>it.id!==state.selected);state.selected=null;updateAnnotationPanels();scheduleDraw();queueDraft()}
function setTool(tool){cancelDraft();state.tool=tool;document.querySelectorAll('[data-tool]').forEach(e=>e.value=tool);document.querySelectorAll('[data-canvas-tool]').forEach(e=>{e.classList.toggle('active',e.dataset.canvasTool===tool);e.setAttribute('aria-pressed',String(e.dataset.canvasTool===tool))});document.querySelectorAll('.viewport canvas').forEach(c=>c.style.cursor=tool==='navigate'?'grab':tool==='select'?'default':'crosshair');scheduleDraw()}
const baseFinish=finishDrawing;finishDrawing=function(){const free=state.tool==='freehand';if(free)state.tool='polygon';baseFinish();if(free)state.tool='freehand';queueDraft()};
const baseDrawAnnotation=drawAnnotation;drawAnnotation=function(ctx,it,s){baseDrawAnnotation(ctx,it,s);if(it.id!==state.selected)return;ctx.fillStyle='#ffc778';for(const [x,y] of it.points){ctx.beginPath();ctx.arc(x,y,3/s,0,Math.PI*2);ctx.fill()}};
function nativePoint(v,e){const t=v.transform,rect=v.querySelector('canvas').getBoundingClientRect();if(!t)return null;const x=(e.clientX-rect.left-t.ox)/t.s,y=(e.clientY-rect.top-t.oy)/t.s;if(x<0||y<0||x>state.meta.shape[3]-1||y>state.meta.shape[2]-1)return null;return [x,y]}
function visibleItems(v){return state.items.filter(it=>it.channel===state.channel&&(v.dataset.kind==='volume'?it.domain==='volume'||it.domain==='slice':it.domain===v.dataset.kind&&(it.domain!=='slice'||it.z===state.z)))}
function selectHit(v,e){const c=v.querySelector('canvas'),rect=c.getBoundingClientRect(),pos=[e.clientX-rect.left,e.clientY-rect.top];let best=null,dist=12;for(const it of visibleItems(v)){it.points.forEach((p,i)=>{const q=v.dataset.kind==='volume'?v.project?.(p[0],p[1],it.domain==='volume'?p[2]:it.z):[v.transform.ox+p[0]*v.transform.s,v.transform.oy+p[1]*v.transform.s];if(!q)return;const d=Math.hypot(q[0]-pos[0],q[1]-pos[1]);if(d<dist){best={it,index:i};dist=d}})}return best}
function volumePoint(v,e){if(!v.project||!v.samplePoints)return null;const rect=v.querySelector('canvas').getBoundingClientRect(),x=e.clientX-rect.left,y=e.clientY-rect.top;let best=null,distance=10;for(const p of v.samplePoints){const q=v.project(p[0],p[1],p[2]),d=Math.hypot(q[0]-x,q[1]-y);if(d<distance){distance=d;best=p.slice(0,3)}}return best}
const baseBindCanvas=bindCanvas;bindCanvas=function(v){baseBindCanvas(v);const c=v.querySelector('canvas'),down=c.onpointerdown,move=c.onpointermove,up=c.onpointerup,cancel=c.onpointercancel;let gesture=null;
 c.onpointerdown=e=>{if(e.button!==0||spaceHeld||state.tool==='navigate'){gesture={pan:true};down(e);return}if(state.tool==='select'){const hit=selectHit(v,e);state.selected=hit?.it.id||null;gesture=hit&&v.dataset.kind!=='volume'?{edit:hit,start:nativePoint(v,e),original:structuredClone(hit.it.points),changed:false}:null;c.setPointerCapture(e.pointerId);scheduleDraw();updateAnnotationPanels();return}
 if(v.dataset.kind==='volume'){gesture={volume:true,x:e.clientX,y:e.clientY};c.setPointerCapture(e.pointerId);return}
 if(state.tool==='freehand'){const p=nativePoint(v,e);if(!p)return;state.pending=[p];state.pendingDomain=v.dataset.kind;gesture={freehand:true};c.setPointerCapture(e.pointerId);scheduleDraw();return}down(e)};
 c.onpointermove=e=>{if(gesture?.edit){const p=nativePoint(v,e);if(!p||!gesture.start)return;if(!gesture.changed){snapshot();gesture.changed=true}gesture.edit.it.points[gesture.edit.index]=p;scheduleDraw();return}if(gesture?.freehand){const p=nativePoint(v,e),last=state.pending.at(-1);if(p&&Math.hypot(p[0]-last[0],p[1]-last[1])*v.transform.s>2){state.pending.push(p);scheduleDraw()}return}if(gesture?.volume)return;if(gesture?.pan&&state.tool!=='navigate'){const old=state.tool;state.tool='navigate';move(e);state.tool=old}else move(e)};
 c.onpointerup=e=>{if(gesture?.edit){if(gesture.changed){queueDraft();updateAnnotationPanels()}gesture=null;return}if(gesture?.freehand){gesture=null;finishDrawing();return}if(gesture?.volume){const g=gesture;gesture=null;if(Math.hypot(e.clientX-g.x,e.clientY-g.y)>4)return;if(state.tool==='polygon'||state.tool==='freehand'){status('Outline cells on the slice pane; 3D supports landmarks and traces');return}const p=volumePoint(v,e);if(!p){status('Click a visible signal point to place a 3D landmark');return}if(state.pending.length&&state.pendingDomain!=='volume'){status('Finish the current drawing first');return}state.pendingDomain='volume';state.pending.push(p);if(state.tool==='point')finishDrawing();else scheduleDraw();status('3D point anchored at X '+Math.round(p[0])+', Y '+Math.round(p[1])+', Z '+(p[2]+1)+' • check depth before accepting');return}if(gesture?.pan&&state.tool!=='navigate'){const old=state.tool;state.tool='navigate';up(e);state.tool=old}else up(e);gesture=null};
 c.onpointercancel=()=>{if(gesture?.edit?.it&&gesture.changed)gesture.edit.it.points=gesture.original;if(gesture?.freehand)cancelDraft();gesture=null;cancel?.();scheduleDraw()};
};
function toolPalette(){const el=document.createElement('div');el.className='floating-tools';el.setAttribute('aria-label','Annotation tools');const defs=[['navigate','↖','Pan','V'],['select','⌖','Select','S'],['point','⊙','Point','P'],['polygon','⬡','Outline','O'],['freehand','〰','Draw','B'],['polyline','⌁','Trace','L']];for(const [tool,icon,label,key] of defs){const b=document.createElement('button');b.dataset.canvasTool=tool;b.textContent=icon+' '+label;b.title=label+' ('+key+')';b.setAttribute('aria-label',label+' tool');b.classList.toggle('active',state.tool===tool);b.onclick=()=>setTool(tool);el.append(b)}const divider=document.createElement('span');divider.className='divider';el.append(divider);for(const [label,title,fn] of [['↶','Undo',()=>undoStudio()],['↷','Redo',()=>undoStudio(true)],['✓','Finish drawing',finishDrawing]]){const b=document.createElement('button');b.textContent=label;b.title=title;b.setAttribute('aria-label',title);b.onclick=fn;el.append(b)}return el}
function decorateAnnotations(){const panel=$('#task-panel'),tool=panel.querySelector('.tool');if(!tool)return;tool.querySelector('h2').textContent='Your annotations';const count=document.createElement('div');count.className='annotation-count';count.innerHTML='<strong>'+state.items.length+'</strong><span class="muted">marks in this scan</span>';tool.querySelector('h2').after(count);const label=document.createElement('input');label.className='annotation-label';label.placeholder='Label, e.g. inner hair cell';label.setAttribute('aria-label','Annotation label');label.value=state.annotationLabel;label.oninput=e=>state.annotationLabel=e.target.value;count.after(label);const controls=document.createElement('div');controls.className='edit-actions';const del=document.createElement('button');del.textContent='Delete selected';del.disabled=!state.selected;del.onclick=removeSelected;controls.append(del);label.after(controls);const sel=tool.querySelector('[data-tool]');if(sel)sel.closest('label').hidden=true;tool.querySelector('[data-undo]').onclick=()=>undoStudio();tool.querySelector('[data-save]').classList.add('primary');tool.querySelector('[data-save]').textContent='Save now';tool.querySelector('[data-save]').onclick=safe(async()=>{await saveAnnotations();saveState('Saved ✓')});const note=document.createElement('p');note.className='help-note';note.textContent='2D: draw on a slice. 3D: place landmarks or trace visible signal points. Depth can be ambiguous—rotate to verify. 3D geometry is saved in JSON/CSV; ImageJ ROIs contain 2D marks.';const details=document.createElement('details');details.innerHTML='<summary>How to draw & exchange files</summary>';details.append(note);[...tool.children].filter(e=>e.tagName==='P').forEach(e=>details.append(e));const imported=tool.querySelector('[data-import]');if(imported)details.append(imported.closest('label'));tool.append(details);tool.querySelector('[data-finish]').parentElement.hidden=true;}
const baseUpdatePanels=updateAnnotationPanels;updateAnnotationPanels=function(){baseUpdatePanels();const count=$('.annotation-count strong');if(count)count.textContent=state.items.length;const del=$('.edit-actions button');if(del)del.disabled=!state.selected};
const baseFillList=fillAnnotationList;fillAnnotationList=function(el){baseFillList(el);[...el.children].forEach((row,i)=>{const it=state.items[i];if(it.label)row.querySelector('span').textContent=it.label+' · '+it.type+' · '+(it.domain==='volume'?'3D':it.domain);row.querySelectorAll('button').forEach(b=>{if(b.textContent==='Show')b.onclick=()=>{state.selected=it.id;state.channel=it.channel;state.mode=it.domain==='volume'?'volume':it.domain;state.z=it.z;$('#channel').value=state.channel;$('#z').value=it.z;renderLayout()}})})};
function recipeParameters(tool){const p={};tool.querySelectorAll('[name]').forEach(n=>p[n.name]=n.type==='checkbox'?n.checked:n.value);delete p.parent;return p}
function applyRecipe(params){state.recipe={...params,parent:''};renderLayout();status('Recipe applied • confirm the channel and preview scope before running')}
function decorateProcess(){const tool=$('#task-panel .tool');if(!tool)return;tool.querySelector('h2').textContent='Build a processing recipe';const rn=document.createElement('input');rn.type='hidden';rn.name='recipe_name';rn.value=state.recipe.recipe_name||'';tool.append(rn);const library=document.createElement('div');library.className='recipe-library';library.innerHTML='<h3>Start with a recipe</h3><p class="muted">Choose a starting point, then map it to your image channel.</p>';const select=document.createElement('select');select.setAttribute('aria-label','Recipe library');select.add(new Option('Choose a recipe…',''));const presets=[{name:'Nuclei · watershed candidates',parameters:{method:'watershed',scope:'volume',factor:2,sigma:1,background:0,min_size:30,distance:5,threshold:1}},{name:'Cell bodies · connected regions',parameters:{method:'otsu',scope:'volume',factor:2,sigma:.6,background:0,min_size:30,threshold:1}},{name:'Neurites · ridge network',parameters:{method:'sato',scope:'volume',factor:2,sigma:0,background:0,min_size:15,threshold:1}}];const all=[...presets,...recipeList];all.forEach((r,i)=>select.add(new Option(r.name,String(i))));select.onchange=()=>{if(select.value!=='')applyRecipe({...all[+select.value].parameters,recipe_name:all[+select.value].name})};library.append(select);tool.querySelector('h2').after(library);const save=document.createElement('div');save.className='recipe-save';save.innerHTML='<label>Save a reusable recipe<input placeholder="e.g. Myo7a · baseline" aria-label="Recipe name"></label><button class="primary">Save recipe</button>';save.querySelector('button').onclick=safe(async()=>{const name=save.querySelector('input').value;const recipe=await api('/api/recipes',{name,parameters:recipeParameters(tool)});recipeList.push(recipe);renderLayout();status('Recipe saved: '+recipe.name)});tool.append(save);tool.querySelector('[data-run]').classList.add('primary');}
const baseCatalog=resultCatalog;resultCatalog=function(){baseCatalog();const search=$('#result-search')?.value.toLowerCase()||'';document.querySelectorAll('.result-button[data-result]').forEach(b=>{const r=state.runs.find(r=>r.id===b.dataset.result);const badge=document.createElement('span');badge.className='run-badge';badge.textContent=r.historical?'◷ Saved output · view only':'● Local method · rerunnable';b.append(badge);b.hidden=!b.textContent.toLowerCase().includes(search)})};$('#result-search').oninput=resultCatalog;
const baseLayout=renderLayout;renderLayout=function(){if(state.tab!=='Annotate')state.tool='navigate';baseLayout();if(!state.meta)return;document.body.classList.toggle('student',state.tab==='Annotate');document.querySelector('.mode-buttons').hidden=state.tab==='Annotate';$('#compare-grid').hidden=state.tab==='Annotate';const host=$('#main-host');host.classList.remove('annotation-layout','compare-four');if(state.tab==='Annotate'){host.replaceChildren(newViewport('slice',false,'annotation-slice'),newViewport('volume',false,'annotation-volume'));host.classList.add('annotation-layout');$('#desk').append(toolPalette());const hint=document.createElement('div');hint.className='canvas-hint';hint.textContent='Space + drag to move · P point · B draw · Enter finish · ⌘ Z undo';$('#desk').append(hint);decorateAnnotations()}else{$('#desk .floating-tools')?.remove();$('#desk .canvas-hint')?.remove();if(state.compareGrid){host.replaceChildren();host.classList.add('compare-four');const ids=['',state.run,...state.runs.filter(r=>r.id!==state.run&&canShow(r,state.mode)).map(r=>r.id)].filter((v,i,a)=>a.indexOf(v)===i).slice(0,4);ids.forEach((id,i)=>{const v=newViewport(state.mode,!id,'grid-'+i);v.overrideRun=id;host.append(v)})}if(state.tab==='Process')decorateProcess()}
 // Remove tools from the previous render without disturbing the image canvases.
 document.querySelectorAll('.floating-tools').forEach((e,i,a)=>{if(i<a.length-1)e.remove()});document.querySelectorAll('.canvas-hint').forEach((e,i,a)=>{if(i<a.length-1)e.remove()});
 host.querySelectorAll('.viewport').forEach((v,i)=>{const name=document.createElement('div');name.className='pane-name';name.textContent=state.tab==='Annotate'?(i?'3D context':'Draw on this slice'):(v.raw?'Reference':'Result');v.append(name)});scheduleDraw();};
const gridButton=document.createElement('button');gridButton.id='compare-grid';gridButton.textContent='⊞ Compare grid';gridButton.onclick=()=>{state.compareGrid=!state.compareGrid;gridButton.classList.toggle('active',state.compareGrid);renderLayout()};$('#more-tools').before(gridButton);
const preview=document.createElement('div');preview.id='import-preview';$('#import-name').after(preview);$('#source-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#import-name').textContent=file.name;$('#import-dialog').showModal();preview.textContent='Reading dimensions…';try{const r=await fetch('/api/inspect-source?'+query({name:file.name}),{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Studio-Request':'1'},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);preview.textContent=d.axes.split('').map((a,i)=>a+' '+d.shape[i]).join(' × ')+' · '+d.dtype+' · '+(file.size/1048576).toFixed(1)+' MB';if(d.series>1)preview.textContent+=' · '+d.series+' series (imports first series only)';}catch(e){preview.textContent=e.message}};
document.addEventListener('keydown',e=>{if(e.target.closest('input,textarea,select')||e.target.isContentEditable)return;if(e.code==='Space'){e.preventDefault();spaceHeld=true}if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undoStudio(e.shiftKey);return}if(e.key==='Enter'&&state.pending.length){e.preventDefault();finishDrawing()}if((e.key==='Delete'||e.key==='Backspace')&&state.selected){e.preventDefault();removeSelected()}if(state.tab==='Annotate'&&!e.metaKey&&!e.ctrlKey){const t={v:'navigate',s:'select',p:'point',o:'polygon',b:'freehand',l:'polyline'}[e.key.toLowerCase()];if(t)setTool(t)}});document.addEventListener('keyup',e=>{if(e.code==='Space')spaceHeld=false});window.addEventListener('blur',()=>spaceHeld=false);
Promise.all([api('/api/recipes'),api('/api/config')]).then(([recipes,config])=>{recipeList=recipes;if(config.shared){const banner=document.createElement('div');banner.className='shared-banner';banner.textContent='Shared public demo · synthetic starter scans · uploads and saved annotations are visible to other visitors · '+config.upload_limit_mb+' MB upload limit';document.querySelector('nav').before(banner)}if(state.meta)renderLayout()}).catch(e=>status(e.message,true));
